---
title: "LAS 6292: Week 12 Notes"
date: "updated: `r Sys.Date()`"
header-includes:
- \AtBeginDocument{\let\maketitle\relax} # this removes default title section
- \usepackage[default]{sourcesanspro}
- \usepackage{fancyhdr} # modify header into left, center, right
- \pagestyle{fancy} # cues the use of fancy headers
- \fancyfoot{} # cues the use of fancy footer
# month & year on header left
- \fancyhead[L]{LAS 6292 Spring `r format(Sys.time(), '%Y')`, EM Bruna} 
# name and page on header right
- \fancyhead[R]{Paperless Data Collection, p. \thepage} 
- \fancyfoot[R]{Last update `r format(Sys.time(), '%d %B %Y')`}
# - \usepackage{setspace}{singlespace} # manipulate line spacing 
- \usepackage{parskip} # manipulate indents and spacing before/after paragra phs 
- \usepackage{xcolor} # changes colors of text
# to center to top level (#) headings (my name) and change color of font
# more info # https://www.ctan.org/pkg/sectsty
- \usepackage{sectsty} \sectionfont{\centering\color{darkmidnightblue}}
# to center to sub-sub-headings (###) and change color of font
- \usepackage{sectsty} \subsectionfont{\color{darkmidnightblue}}
# http://latexcolor.com/ to choose colors
# define the colors used above with rgb codes
- \definecolor{darkcerulean}{rgb}{0.03, 0.27, 0.49}
- \definecolor{darkmidnightblue}{rgb}{0.0, 0.2, 0.4}
# - \usepackage{ragged2e}
# - \setlength\RaggedRightParindent{15pt}
# - \RaggedRight - # make the right margin ragged
# https://tex.stackexchange.com/questions/258714/prevent-hyphenation-across-lines-enforce-right-margin
# - \hyphenpenalty=10000 #to suppress ordinary hyphenation
# - \exhyphenpenalty=10000 #to prohibit line breaks at explicit hyphens.
# - \setstretch{1.0}

# https://babichmorrowc.github.io/post/changing-fonts-in-rmarkdown-pdfs/

mainfont: SourceSansPro
geometry: margin=1in
fontsize: 12pt
linkcolor: blue
urlcolor: blue
output: pdf_document
knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile,
  encoding = encoding,
  output_dir = "./static/uploads/notes")
  })
---


```{r setup, include=FALSE}
library(knitr)
library(rmdformats)
knitr::opts_chunk$set(echo = TRUE)
## Global options
options(max.print="75")
opts_chunk$set(echo=FALSE,
	             cache=TRUE,
               prompt=FALSE,
               tidy=TRUE,
               comment=NA,
               message=FALSE,
               warning=FALSE)
opts_knit$set(width=75)
```
# Paperless Data Collection

## Tools & Resources

1. [EpiCollect user's guide](https://docs.epicollect.net/)

2. Best data app for interactive voice data collection: [Magpi](https://www.magpi.com/blog/interactive-data-collection) (Web, iOS, Android)

3. Lists of useful apps for data collection in the field: 

    * [Bruna Lab Super-List](https://brunalab.github.io/apps_for_fieldwork/) (start here)
    * [[list 2]](https://www.teamscopeapp.com/mobile-data-collection-guide/7-mobile-data-collection-apps-for-field-research)
    * [[list 3]](https://www.researchgate.net/post/Please-could-you-indicate-some-useful-android-apps-for-Ecology-Forestry-or-Environment)
    * [[list 4]](https://writingfornature.wordpress.com/2012/08/17/tools-for-the-modern-primate-apps-for-field-work/)
    * [[list 5]](https://ayrnstories.wordpress.com/2017/08/09/apps-in-ecological-research/)
    * [[list 6]](https://www.commonsense.org/education/top-picks/excellent-ecology-and-environmental-science-apps-games-and-websites)
    * [[list 7]](https://www.researchgate.net/post/What_essential_android_apps_should_a_field_biologist_know_about)




1. Paid platforms for paperless data collection

    * [Fulcrum](https://www.fulcrumapp.com/); [link to post](https://gadgets360.com/science/features/fulcrum-app-science-fieldwork-data-collection-2294662) describing how it was used by an NGO.
    * [ODK](https://getodk.org)

## Sources & Additional Reading


1. [Streamlining Field Data Collection with Mobile Apps](https://eos.org/science-updates/streamlining-field-data-collection-mobile-apps)

1. [Research at Home: Using a Smartphone for Data Collection](https://www.societyforscience.org/research-at-home/using-smartphone-for-data-collection/)  
1. [Keep calm and go paperless: Electronic lab notebooks can improve your research](https://openworking.wordpress.com/2019/07/05/keep-calm-and-go-paperless-electronic-lab-notebooks-can-improve-your-research/)

1. [NOAA Pathways to paperless Data Collection](https://www.fisheries.noaa.gov/feature-story/pathway-paperless-data-collection)

1. Thieler ER, Zeigler SL, Winslow LA, Hines MK, Read JS, Walker JI (2016) Smartphone-Based Distributed Data Collection Enables Rapid Assessment of Shorebird Habitat Suitability. PLoS ONE 11(11): e0164979. [link](https://doi.org/10.1371/journal.pone.0164979)

1. Teacher, A. G., Griffiths, D. J., Hodgson, D. J., & Inger, R. (2013). Smartphones in ecology and evolution: a guide for the app-rehensive. Ecology and evolution, 3(16), 5268–5278. [link](https://doi.org/10.1002/ece3.888)

1. Palumbo, M.J., Johnson, S.A., Mundim, F.M., Lau, A., Wolf, A.C., Arunachalam, S., Gonzalez, O., Ulrich, J.L., Washuta, A. and Bruna, E.M. (2012), Harnessing Smartphones for Ecological Education, Research, and Outreach. The Bulletin of the Ecological Society of America, 93: 390-393.  [link](https://esajournals.onlinelibrary.wiley.com/doi/10.1890/0012-9623-93.4.390)

1. Rayhan, R. U., Zheng, Y., Uddin, E., Timbol, C., Adewuyi, O., & Baraniuk, J. N. (2013). Administer and collect medical questionnaires with Google documents: a simple, safe, and free system. Applied Medical Informatics, 33(3), 12-21. [link](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3884902/) 

1. Moylan, C. A., Derr, A. S., & Lindhorst, T. (2013). Increasingly mobile: How new technologies can enhance qualitative research. Qualitative social work: research and practice, 14(1), 36-47. [link](https://journals.sagepub.com/doi/10.1177/1473325013516988)

1. Aanensen DM, Huntley DM, Feil EJ, al-Own F, Spratt BG (2009) EpiCollect: Linking Smartphones to Web Applications for Epidemiology, Ecology and Community Data Collection. PLoS ONE 4(9): e6968. [link](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0006968)

