---
title: "LAS 6292: METADATA"
date: "updated: `r Sys.Date()`"
header-includes:
   - \usepackage[default]{sourcesanspro}
   - \usepackage[T1]{fontenc}
mainfont: SourceSansPro
geometry: margin=1in
fontsize: 12pt
linkcolor: blue
urlcolor: blue
output:
  pdf_document: default
  html_document:
    df_print: paged
  rmdformats::robobook: default
---


```{r setup, include=FALSE}
library(knitr)
library(rmdformats)

## Global options
options(max.print="75")
opts_chunk$set(echo=FALSE,
	             cache=TRUE,
               prompt=FALSE,
               tidy=TRUE,
               comment=NA,
               message=FALSE,
               warning=FALSE)
opts_knit$set(width=75)
```

# **Breakout (40 min): ** How easy is it to find and understand metadata associated with papers?

## Instructions

Follow the links to these pages, where you will find the data and metadata from some previously published papers. Look over the data and metadata and discuss the following:

1. Can you explain the variables they collected?

2. Do the data and metadata appear to adhere to the FAIR Principles? 
  
    * Findable: persistent identifiers & basic machine-actionable metadata
    * Accessible: can be read by machines & humans
    * Interoperable: use shared vocabularies / ontologies, machine-accessible (meta)data
    * Re-Usable: descriptions allow others to reuse and link with other data sources


2. Did they include the 5 metadata descriptors?

    * Class I: alert potential secondary users to the existence of data sets that fall within specific temporal, spatial, and thematic domains. 
    * Class II: describe the research resulting in a data set. 
    * Class III: status of the data set and information on its accessibility. 
    * Class IV: all the attributes related to the structure of the data file. 
    * Class V: all other related information that might be necessary for secondary usage, publishing the data set, or auditing the data set. 

3. Does anything else stand out about the data metadata files?


## (Meta)Data Sets
For Numbers 1-4, click on the light blue box with an arrow in the upper right corner that says "Download dataset". 

1. [Data from: Mammal diversity and metacommunity dynamics in urban green spaces: implications for urban wildlife conservation](https://datadryad.org/stash/dataset/doi:10.5061/dryad.9mf02)

2. [Data from: The avifauna of the Galapagos Islands](https://datadryad.org/stash/dataset/doi:10.5061/dryad.156)

3. [Data from: Effect of mutualist partner identity on plant demography](https://datadryad.org/stash/dataset/doi:10.5061/dryad.5kc45)

4. [Data from: Elevated pCO2 affects tissue biomass composition, but not calcification, in a reef coral under two light regimes](https://datadryad.org/stash/dataset/doi:10.5061/dryad.5vg70)

For #5 you should be able to click on the button to the right that sats "Preview this file".

5. [Data from: The moral philosophy of nature: Spiritual Amazonian conceptualizations of the environment](https://www.openicpsr.org/openicpsr/project/116962/version/V1/view?path=/openicpsr/116962/fcr:versions/V1/The-moral-philosophy-of-nature-Spiritual-Amazonian-conceptualizations-of-the-environment.pdf&type=file)


For #6 you should be able to see the metadata in the different tabs without downloading anything. 

6. [Data from: Monitoring the Future: A Continuing Study of American Youth (12th-Grade Survey), 2018 (ICPSR 37416)](https://www.icpsr.umich.edu/web/NAHDAP/studies/37416)


For # 7, scroll to the bottom of the page where it says "Data supplements / Supporting Information / Files in this Data Supplement:"

7. [Data from: How stereotypes impair women’s careers in science](https://www.pnas.org/content/111/12/4403/tab-figures-data)