---
title: 'Week 2: In-Class Assignment'
# author: "Emilio M. Bruna"
# date: "last update: `r format(Sys.time(), '%d %B %Y')`"
# header-includes:
#    - \usepackage[default]{sourcesanspro}
#    - \usepackage[T1]{fontenc}
mainfont: SourceSansPro
geometry: margin=1in
fontsize: 12pt
linkcolor: blue
urlcolor: blue
output:
  pdf_document: default
  # html_document:
  #   df_print: paged
  # rmdformats::robobook: default
header-includes:
- \AtBeginDocument{\let\maketitle\relax} # this removes default title section
- \usepackage[default]{sourcesanspro}
- \usepackage{fancyhdr} # modify header into left, center, right
- \pagestyle{fancy} # cues the use of fancy headers
- \fancyfoot{} # cues the use of fancy footer
# month & year on header left
- \fancyhead[L]{`r format(Sys.time(), '%B %Y')`} 
# name and page on header right
- \fancyhead[R]{LAS 6292 Assignment, p. \thepage} 
# - \usepackage{setspace}{singlespace} # manipulate line spacing 
- \usepackage{lscape}
- \usepackage{parskip} # manipulate indents and spacing before/after paragraphs 
- \usepackage{xcolor} # changes colors of text
# to center to top level (#) headings (my name) and change color of font
# more info # https://www.ctan.org/pkg/sectsty
- \usepackage{sectsty} \sectionfont{\centering\color{darkmidnightblue}}
# to center to sub-sub-headings (###) and change color of font
- \usepackage{sectsty} \subsectionfont{\color{darkmidnightblue}}
# http://latexcolor.com/ to choose colors
# define the colors used above with rgb codes
- \definecolor{darkcerulean}{rgb}{0.03, 0.27, 0.49}
- \definecolor{darkmidnightblue}{rgb}{0.0, 0.2, 0.4}
# - \usepackage{ragged2e}
# - \setlength\RaggedRightParindent{15pt}
# - \RaggedRight - # make the right margin ragged
# https://tex.stackexchange.com/questions/258714/prevent-hyphenation-across-lines-enforce-right-margin
# - \hyphenpenalty=10000 #to suppress ordinary hyphenation
# - \exhyphenpenalty=10000 #to prohibit line breaks at explicit hyphens.
# - \setstretch{1.0}

# https://babichmorrowc.github.io/post/changing-fonts-in-rmarkdown-pdfs/

---


```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = FALSE,message=FALSE,warning=FALSE)
library(tidyverse)
library(kableExtra)
```


<!-- \begin{landscape} -->

```{r MastersCmte, echo=FALSE,message = FALSE,warning=FALSE}

prop_or_not<-read_csv("file_formats.csv") %>% 
  replace_na(list('open source' = " "))
kbl(prop_or_not,digits = 1,
                  format = "latex",
                  align="l",
        longtable = T, 
    col.names = NULL,
                  row.names = FALSE,
                  booktabs=T,
                  linesep = "") %>%
  kable_styling(bootstrap_options = c("hover"),
                latex_options = c("scale_down"),
                full_width = F,
                font_size = 10,
                position = "left") %>% 
  column_spec(1, width = "10em") %>% 
  column_spec(2, width = "30em")  %>% 
  column_spec(3, width = "5em")  %>% 
  row_spec(1:70,hline_after=TRUE)
```
<!-- \end{landscape} -->




