---
title: "LAS 6292 Breakout Week 2: Backup Interview"
author: "Emilio M. Bruna"
mainfont: SourceSansPro
geometry: margin=1in
fontsize: 12pt
linkcolor: blue
urlcolor: blue
output:
  pdf_document: default
  # html_document:
  #   df_print: paged
  # rmdformats::robobook: default
header-includes:
- \AtBeginDocument{\let\maketitle\relax} # this removes default title section
- \usepackage[default]{sourcesanspro}
- \usepackage{fancyhdr} # modify header into left, center, right
- \pagestyle{fancy} # cues the use of fancy headers
- \fancyfoot{} # cues the use of fancy footer
# month & year on header left
- \fancyhead[L]{LAS 6292, Spring `r format(Sys.time(), '%Y')`} 
# name and page on header right
- \fancyhead[R]{Breakout - Backup Interview, p. \thepage} 
# - \usepackage{setspace}{singlespace} # manipulate line spacing 
- \usepackage{parskip} # manipulate indents and spacing before/after paragraphs 
- \usepackage{xcolor} # changes colors of text
# to center to top level (#) headings (my name) and change color of font
# more info # https://www.ctan.org/pkg/sectsty
- \usepackage{sectsty} \sectionfont{\centering\color{darkmidnightblue}}
# to center to sub-sub-headings (###) and change color of font
- \usepackage{sectsty} \subsectionfont{\color{darkmidnightblue}}
# http://latexcolor.com/ to choose colors
# define the colors used above with rgb codes
- \definecolor{darkcerulean}{rgb}{0.03, 0.27, 0.49}
- \definecolor{darkmidnightblue}{rgb}{0.0, 0.2, 0.4}
# - \usepackage{ragged2e}
# - \setlength\RaggedRightParindent{15pt}
# - \RaggedRight - # make the right margin ragged
# https://tex.stackexchange.com/questions/258714/prevent-hyphenation-across-lines-enforce-right-margin
# - \hyphenpenalty=10000 #to suppress ordinary hyphenation
# - \exhyphenpenalty=10000 #to prohibit line breaks at explicit hyphens.
# - \setstretch{1.0}

# https://babichmorrowc.github.io/post/changing-fonts-in-rmarkdown-pdfs/
---
## DATA PROTECTION AND BACKUP INTERVIEW

Please ask each other these questions and then briefly discuss and summarize the responses. Keep the answers anonymous. The goal is to document the range of answers to these questions, so you can summarize or give more detailed answers about individuals as needed.
 

1.	Does your advisor / lab / research group have formal policies that govern your data storage, protection, and backup?

2.	Are you currently backing up your research data?

3.	Do you have a ‘backup plan’ document?

4.	How frequently are you backing up your research data? 

5.	Is it Partial (incremental) or full backup? 

6.	Where are files backed up? 

7.	What metadata accompanies these backups? 

8.	How do you verify that a backup has been successfully performed? 

9.	Have you ever attempted to read data from older backups? 

10.	Have you ever had to restore a file from a backup version?

11.	Are you working with data requiring additional protection due to privacy or security concerns? 

12.	If so, what are the additional safeguards you have implemented?

13.	Where and how are your original data collection instruments or samples stored/protected?

