---
title: "Week 2: File names, formats, & organization; Data Storage & Backup"
author: "Emilio M. Bruna"
mainfont: SourceSansPro
geometry: margin=1in
fontsize: 12pt
linkcolor: blue
urlcolor: blue
output:
  pdf_document: default
  # html_document:
  #   df_print: paged
  # rmdformats::robobook: default
header-includes:
- \AtBeginDocument{\let\maketitle\relax} # this removes default title section
- \usepackage[default]{sourcesanspro}
- \usepackage{fancyhdr} # modify header into left, center, right
- \pagestyle{fancy} # cues the use of fancy headers
- \fancyfoot{} # cues the use of fancy footer
# month & year on header left
- \fancyhead[L]{LAS 6292 Spring `r format(Sys.time(), '%Y')`, EM Bruna} 
# name and page on header right
- \fancyhead[R]{Class Outline - Week 2, p. \thepage} 
- \fancyfoot[L]{Last update `r format(Sys.time(), '%d %B %Y')`}
# - \usepackage{setspace}{singlespace} # manipulate line spacing 
- \usepackage{parskip} # manipulate indents and spacing before/after paragraphs 
- \usepackage{xcolor} # changes colors of text
# to center to top level (#) headings (my name) and change color of font
# more info # https://www.ctan.org/pkg/sectsty
- \usepackage{sectsty} \sectionfont{\centering\color{darkmidnightblue}}
# to center to sub-sub-headings (###) and change color of font
- \usepackage{sectsty} \subsectionfont{\color{darkmidnightblue}}
# http://latexcolor.com/ to choose colors
# define the colors used above with rgb codes
- \definecolor{darkcerulean}{rgb}{0.03, 0.27, 0.49}
- \definecolor{darkmidnightblue}{rgb}{0.0, 0.2, 0.4}
# - \usepackage{ragged2e}
# - \setlength\RaggedRightParindent{15pt}
# - \RaggedRight - # make the right margin ragged
# https://tex.stackexchange.com/questions/258714/prevent-hyphenation-across-lines-enforce-right-margin
# - \hyphenpenalty=10000 #to suppress ordinary hyphenation
# - \exhyphenpenalty=10000 #to prohibit line breaks at explicit hyphens.
# - \setstretch{1.0}

# https://babichmorrowc.github.io/post/changing-fonts-in-rmarkdown-pdfs/
---

## Pre-Class Preparation & Materials Needed (Instructor):  

**Send in an email to students:  **

  * Confirmation of room and zoom link
  * Remind students to bring their computers
  * Make sure you know if everyone has R and instlled; level of R fluency
  * Snacks
  * Copies of the syllabus
  * Copy of Course Roster
  * Flip charts and markers
  * Dry write markers
  * Tent cards for student names
      


## Objectives and Competencies for this session:  

  * Describe and implement conventions for proper naming of files 
  * Explain the difference between proprietary and open formats
  * Learn how to efficiently organize their research data files
  * Learn the preferred format for storing and archiving different types of data files
  * Become familiar with different options for cloud data storage and backup 
  * Develop and implement a plan for short- and long-term data storage, back-up, and archiving
  * Learn rules and policies for data security 
  * Become familiar with tools for such tasks as batch renaming of files, cloud data storage, and automated data backup.
  * Explain options for a long-term sustainable preservation strategy/policy for your data (e.g., discipline specific, institutional, departmental, individual).
  * Address the need for conversion to standard formats needed for re-use
  * Perform basic archival processes: checksum, auditing, format migration, etc.
  * Understand costs & time lines for data storage, management tools and services


## Pre-class Preparation (Students):

* **Readings: **
    1.  Jan Čurn. 2014. How a bug in Dropbox permanently deleted my 8000 photos.  [[read online]](https://medium.com/@jancurn/how-bug-in-dropbox-permanently-deleted-my-8000-photos-cb7dcf13647b) [[download pdf]](https://github.com/BrunaLab/LAS6292_DataManagement/blob/master/instructor-materials/readings/Curn_2014.pdf)

    2.  PSA: Scrivener, Data Integrity and You. Or, How To Avoid Data Loss Heartbreak.  [[read online]](https://www.reddit.com/r/writing/comments/62hr7o/psa_scrivener_data_integrity_and_you_or_how_to/) [[download pdf]](https://github.com/BrunaLab/LAS6292_DataManagement/blob/master/instructor-materials/readings/Scrivener_PSA.pdf)

    4.  Hart EM et al. (2016) Ten Simple Rules for Digital Data Storage. PLoS Comput Biol 12(10): e1005097. [[read online]](https://doi.org/10.1371/journal.pcbi.1005097) [[download pdf]](https://github.com/BrunaLab/LAS6292_DataManagement/blob/master/instructor-materials/readings/Hart_etal_2016.PDF).
    
    3. Panzarino, M. 2012. How Pixar’s Toy Story 2 was deleted twice, once by technology and again for its own good. TNW.  [[read online]](https://thenextweb.com/media/2012/05/21/how-pixars-toy-story-2-was-deleted-twice-once-by-technology-and-again-for-its-own-good/)  [[download pdf]]

* **Online Lectures:** 

    1. Video on [Project Organization](https://youtu.be/h1hIKNC64ac)
    2. Video on [File Names](https://youtu.be/BMwI7ubvTnE)
    3. Video on [Storage and Backup](https://youtu.be/H06GSL66Mec)

## Class Outline

```{r timer, echo=FALSE}
intro <- 25
jeopardy <- 35
snack_break <- 10
breakout1 <- 25
breakout1_return <- 30

total_time <- intro + jeopardy + 
  breakout1 + snack_break + breakout1_return 

time_remain <- 180 - total_time
```

<!-- 1. Turn on zoom captioning  -->

1. **Block 1: (`r intro` min): ** 

    a. Address any questions from last week
    b. Overview of today's activities. 

2. **Block 2: File Format Competition (`r jeopardy` min)**

<!-- These are common file formats used to collect, analyze, and store data. Can you tell me what the extensions stand for? Winner gets swag... -->


3. **Snack Break (`r snack_break` min)**

3. **Block 3: Breakout 1 (`r breakout1` min): **

      a. Discussion of Data Security and Backup in the field
      
4. **Block 4: Breakout 1 return results (`r breakout1_return` min)** 

    a. Key message - assume the worst case scenario. become paranoid. embrace neurosis. then relax because the plan is in place and all possibilities have been acounted for. 

8. **Block 5: Breakout 2 (`r time_remain` min) ** 

    a. Interview Breakout, collect answers on google doc or word doc and submit with Assignment 2
    b. Remainder of time is to work on Assignment 2. Instructor regularly checking in on students 


9. Semi-joking: objectives for today are to instill:

    a. a sense of paranoia that everything that could go wrong with notebooks, datasheets, samples, and their backups will - fire, lost mail, flooding, demonic intervention - so that we plan for all scenarios. Can now photograph records, backup, leacve portabl;e hard drives, abc samples, deposit in collections, take a portable scanner to the field...whatever.  As researchers and grad students there is plenty to stress about as it is, lets, takle this stress away so that you can stress about other stuff that "matters". 
    b. FOcused Laziness: we want to do this in a way that is as automated (and automatic) as possible. This will mean less work! And that means more time to do other things, be it research or relaxation.
    


## After class: 

* Be sure you complete and submit the assignment by 9 am Monday
* Prepare for next session (assigned reading, videos, etc).


