---
title: "LAS 6292: Week 10 In-class Breakout 2"
date: "updated: `r Sys.Date()`"
header-includes:
- \AtBeginDocument{\let\maketitle\relax} # this removes default title section
- \usepackage[default]{sourcesanspro}
- \usepackage{fancyhdr} # modify header into left, center, right
- \pagestyle{fancy} # cues the use of fancy headers
- \fancyfoot{} # cues the use of fancy footer
# month & year on header left
- \fancyhead[L]{LAS 6292 Spring `r format(Sys.time(), '%Y')`, EM Bruna} 
# name and page on header right
- \fancyhead[R]{Transcription and Translation Breakout 2, p. \thepage} 
- \fancyfoot[R]{Last update `r format(Sys.time(), '%d %B %Y')`}
# - \usepackage{setspace}{singlespace} # manipulate line spacing 
- \usepackage{parskip} # manipulate indents and spacing before/after paragra phs 
- \usepackage{xcolor} # changes colors of text
# to center to top level (#) headings (my name) and change color of font
# more info # https://www.ctan.org/pkg/sectsty
- \usepackage{sectsty} \sectionfont{\centering\color{darkmidnightblue}}
# to center to sub-sub-headings (###) and change color of font
- \usepackage{sectsty} \subsectionfont{\color{darkmidnightblue}}
# http://latexcolor.com/ to choose colors
# define the colors used above with rgb codes
- \definecolor{darkcerulean}{rgb}{0.03, 0.27, 0.49}
- \definecolor{darkmidnightblue}{rgb}{0.0, 0.2, 0.4}
# - \usepackage{ragged2e}
# - \setlength\RaggedRightParindent{15pt}
# - \RaggedRight - # make the right margin ragged
# https://tex.stackexchange.com/questions/258714/prevent-hyphenation-across-lines-enforce-right-margin
# - \hyphenpenalty=10000 #to suppress ordinary hyphenation
# - \exhyphenpenalty=10000 #to prohibit line breaks at explicit hyphens.
# - \setstretch{1.0}

# https://babichmorrowc.github.io/post/changing-fonts-in-rmarkdown-pdfs/

mainfont: SourceSansPro
geometry: margin=1in
fontsize: 12pt
linkcolor: blue
urlcolor: blue
output:
  pdf_document: default
  # html_document:
  #   df_print: paged
  # rmdformats::robobook: default
---


```{r setup, include=FALSE}
library(knitr)
library(rmdformats)
knitr::opts_chunk$set(echo = TRUE)
## Global options
options(max.print="75")
opts_chunk$set(echo=FALSE,
	             cache=TRUE,
               prompt=FALSE,
               tidy=TRUE,
               comment=NA,
               message=FALSE,
               warning=FALSE)
opts_knit$set(width=75)
```

# Breakout 2: TRANSCRIPTION 

We will try transcribing audio recorded in different languages using different online services; note that not all languages will be available in all services. 

## STEP 1. Sign up for an account 

Sign up for accounts with the following transcription services. You can cancel the accounts if you think you won't need them afterwards. Additional details and links to tutorials are available on the _Resources_ page.

1. [Otter.ai](https://otter.ai/login).

2. [Happy Scribe](https://www.happyscribe.com/)

3. [Watson](https://speech-to-text-demo.ng.bluemix.net/); note the "detect multiple speakers" option.


## STEP 2: Transcribe 

1. Download the following audio files. Note that the link takes you to the page where the file is archived; click the 'download' button to save it to your computer.

    * [`turkish_audio.mp3`](https://github.com/BrunaLab/LAS6292_DataManagement/blob/37ebab30eb5744a2a501572cd3b7fc2772009a34/content/instructor-materials/class-sessions/11-transcription-translation/translation_audio/turkish_audio.mp3)  

    * [`spanish_audio1_voice.mp3`](https://github.com/BrunaLab/LAS6292_DataManagement/blob/master/content/instructor-materials/class-sessions/11-transcription-translation/translation_audio/spanish_audio_1voice.mp3)  

<!-- 1. `portuguese_audio.mp3`  -->
<!-- indonesian_audio.mp3 -->
<!-- mandarin1_audio.mp3 -->
<!-- mandarin2_audio.mp3 -->
<!-- english_audio.mp3   -->


2. Now transcribe these audio files with each of the different services (note that not all services will transcribe all languages). 

3. Save the resulting transcriptions files as Google Docs or .txt files. Use the following naming convention: `transcription_[language]_[name of service]`  


## STEP 3: Translate

1. Translating these transcriptions to English with Google Docs 

2. Save with the following file names: `translation_[language]_[name of transcription service]` (e.g., `translation_spanish_happyscribe`)  

3. Paste the *translations from transcription* and the *translation from the original .txt files* (used in the translation breakout) into the [Text Comparison Website](https://www.diffchecker.com/diff). You may have to adjust the spacing in the text files to make the text align. 

## STEP 4: Discuss

1. Do the transcriptions appear accurate? 

2. What about the translations from transcriptions? Is there a loss in quality when going from audio-to-text-to-English when compared with text-to-English

3. What would be the best approach for research: 

    a. transcribing, editing the transcription, then translating, or 
    b. transcribing, translating, then correcting? 
