---
title: "LAS 6292: Week 10: In-Class Breakout 1"
date: "updated: `r Sys.Date()`"
header-includes:
- \AtBeginDocument{\let\maketitle\relax} # this removes default title section
- \usepackage[default]{sourcesanspro}
- \usepackage{fancyhdr} # modify header into left, center, right
- \pagestyle{fancy} # cues the use of fancy headers
- \fancyfoot{} # cues the use of fancy footer
# month & year on header left
- \fancyhead[L]{LAS 6292 Spring `r format(Sys.time(), '%Y')`, EM Bruna} 
# name and page on header right
- \fancyhead[R]{Transcription and Translation Breakout 1, p. \thepage} 
- \fancyfoot[R]{Last update `r format(Sys.time(), '%d %B %Y')`}
# - \usepackage{setspace}{singlespace} # manipulate line spacing 
- \usepackage{parskip} # manipulate indents and spacing before/after paragra phs 
- \usepackage{xcolor} # changes colors of text
# to center to top level (#) headings (my name) and change color of font
# more info # https://www.ctan.org/pkg/sectsty
- \usepackage{sectsty} \sectionfont{\centering\color{darkmidnightblue}}
# to center to sub-sub-headings (###) and change color of font
- \usepackage{sectsty} \subsectionfont{\color{darkmidnightblue}}
# http://latexcolor.com/ to choose colors
# define the colors used above with rgb codes
- \definecolor{darkcerulean}{rgb}{0.03, 0.27, 0.49}
- \definecolor{darkmidnightblue}{rgb}{0.0, 0.2, 0.4}
# - \usepackage{ragged2e}
# - \setlength\RaggedRightParindent{15pt}
# - \RaggedRight - # make the right margin ragged
# https://tex.stackexchange.com/questions/258714/prevent-hyphenation-across-lines-enforce-right-margin
# - \hyphenpenalty=10000 #to suppress ordinary hyphenation
# - \exhyphenpenalty=10000 #to prohibit line breaks at explicit hyphens.
# - \setstretch{1.0}

# https://babichmorrowc.github.io/post/changing-fonts-in-rmarkdown-pdfs/

mainfont: SourceSansPro
geometry: margin=1in
fontsize: 12pt
linkcolor: blue
urlcolor: blue
output:
  pdf_document: default
  # html_document:
  #   df_print: paged
  # rmdformats::robobook: default
---


```{r setup, include=FALSE}
library(knitr)
library(rmdformats)
knitr::opts_chunk$set(echo = TRUE)
## Global options
options(max.print="75")
opts_chunk$set(echo=FALSE,
	             cache=TRUE,
               prompt=FALSE,
               tidy=TRUE,
               comment=NA,
               message=FALSE,
               warning=FALSE)
opts_knit$set(width=75)
```

## Breakout 1: Translation of Texts into English


1. Download the following .txt files. Note that the link takes you to a page on your browsewr; use "save this page as" to download it to your computer. 

[`spanish_text_1voice.txt`](https://raw.githubusercontent.com/BrunaLab/LAS6292_DataManagement/master/content/instructor-materials/class-sessions/11-transcription-translation/translation_text/spanish_text_1voice.txt)

[`turkish_text.txt`](https://raw.githubusercontent.com/BrunaLab/LAS6292_DataManagement/master/content/instructor-materials/class-sessions/11-transcription-translation/translation_text/turkish_text.txt)

[`spanish_text_interview.txt`](https://raw.githubusercontent.com/BrunaLab/LAS6292_DataManagement/master/content/instructor-materials/class-sessions/11-transcription-translation/translation_text/spanish_text_1voice.txt)

<!-- [`spanish_text_interview.txt`] -->




## STEP 1: Text Translations

Translate the text files with MS Word and Google Docs  

1. Google Docs: [in-doc translation](https://support.google.com/docs/answer/187189?co=GENIE.Platform%3DDesktop&hl=en) (create a new google doc, cut-and-paste the text into the Google Doc, save it, and translate)

2. MS Word: [in-doc translation](https://support.microsoft.com/en-us/topic/translate-text-into-a-different-language-287380e4-a56c-48a1-9977-f2dca89ce93f) 


## STEP 2: Save

Save the translations in your Google Drive in a folder called "class_translations" with the following file names and formats:

1. MS Word: .txt file: `MSWord_[original language]_to_english.txt`  

1. Google: new GoogleDoc: `google_[original language]_to_english`

## STEP 3: Compare

1. Paste the translations into the [Text Comparison Website](https://www.diffchecker.com/diff). Note that you may have to adjust the spacing in the text files to make the text align.  

## STEP 4: Discuss  

1. Are there are any differences in the way key words or concepts were translated? 

2. Are there circumstances under which these could influence the interpretation of the writer's intent? Subtleties of language like formality of tense, tone, or meaning?

3. Do any of them seem "better" or "more accurate"? 

