# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  # - name: Home Page
  #   url: /
  #   weight: 10
  - name: Instructor
    url: docs/instructor-info
    weight: 10
  - name: Syllabus & Schedule
    url: docs/course-schedule
    weight: 20
  - name: Assignments
    url: docs/assignments
    weight: 30
  - name: Resources
    url: docs/resources
    weight: 40
