---
title: 'Week 2: In-Class Assignment'
# author: "Emilio M. Bruna"
# date: "last update: `r format(Sys.time(), '%d %B %Y')`"
# header-includes:
#    - \usepackage[default]{sourcesanspro}
#    - \usepackage[T1]{fontenc}
mainfont: SourceSansPro
geometry: margin=1in
fontsize: 12pt
linkcolor: blue
urlcolor: blue
output:
  pdf_document: default
  # html_document:
  #   df_print: paged
  # rmdformats::robobook: default
header-includes:
- \AtBeginDocument{\let\maketitle\relax} # this removes default title section
- \usepackage[default]{sourcesanspro}
- \usepackage{fancyhdr} # modify header into left, center, right
- \pagestyle{fancy} # cues the use of fancy headers
- \fancyfoot{} # cues the use of fancy footer
# month & year on header left
- \fancyhead[L]{`r format(Sys.time(), '%B %Y')`} 
# name and page on header right
- \fancyhead[R]{LAS 6292 Assignment, p. \thepage} 
# - \usepackage{setspace}{singlespace} # manipulate line spacing 
- \usepackage{parskip} # manipulate indents and spacing before/after paragraphs 
- \usepackage{xcolor} # changes colors of text
# to center to top level (#) headings (my name) and change color of font
# more info # https://www.ctan.org/pkg/sectsty
- \usepackage{sectsty} \sectionfont{\centering\color{darkmidnightblue}}
# to center to sub-sub-headings (###) and change color of font
- \usepackage{sectsty} \subsectionfont{\color{darkmidnightblue}}
# http://latexcolor.com/ to choose colors
# define the colors used above with rgb codes
- \definecolor{darkcerulean}{rgb}{0.03, 0.27, 0.49}
- \definecolor{darkmidnightblue}{rgb}{0.0, 0.2, 0.4}
# - \usepackage{ragged2e}
# - \setlength\RaggedRightParindent{15pt}
# - \RaggedRight - # make the right margin ragged
# https://tex.stackexchange.com/questions/258714/prevent-hyphenation-across-lines-enforce-right-margin
# - \hyphenpenalty=10000 #to suppress ordinary hyphenation
# - \exhyphenpenalty=10000 #to prohibit line breaks at explicit hyphens.
# - \setstretch{1.0}

# https://babichmorrowc.github.io/post/changing-fonts-in-rmarkdown-pdfs/

---

<!-- Note: to rendr as pdf delete the \newline -->
<!-- # **LAS 6292 WEEK 2 ASSIGNMENT: Data Storage and Backup**  -->

## BREAKOUT EXERCISE: FIELD DATA STORAGE AND BACKUP

Robin is a graduate student studying Malaria in Tanzania. The research project requires visiting communities, collecting mosquitoes from different sources of standing water (for later identification at the FLMNH and statistical analyses of mosquito diversity and abundance) and conducting semi--structured interviews in the community, where people are asked such things as their age, family income, their access to health care, if they have ever had malaria, their family income, use of mosquito nets. Answers are recorded on data sheets, but the interviews are also recorded with the cell phone for later transcription. Robin also takes pictures of houses to document standing water sources. Throughout the day Robin records observations in a notebook.  

Robin is staying in a house where there is electricity for a laptop. Once every two weeks Robin goes into town, where there is usually good internet access at the university. 

What steps should Robin take in the field to safeguard the data collected in the field? 

## In-class assignment/Homework

###  Data Protection & Backup Interview

Please ask each other these questions and then briefly discuss and summarize the responses. Keep the answers anonymous. The goal is to document the range of answers to these questions, so you can summarize or give more detailed answers about individuals as needed.

1.	Does your advisor / lab / research group have formal policies that govern your data storage, protection, and backup?

2.	Are you currently backing up your research data?

3.	Do you have a ‘backup plan’ document?

4.	How frequently are you backing up your research data? 

5.	Is it Partial (incremental) or full backup? 

6.	Where are files backed up? 

7.	What metadata accompanies these backups? 

8.	How do you verify that a backup has been successfully performed? 

9.	Have you ever attempted to read data from older backups? 

10.	Have you ever had to restore a file from a backup version?

11.	Are you working with data requiring additional protection due to privacy or security concerns? 

12.	If so, what are the additional safeguards you have implemented?

13.	Where and how are your original data collection instruments or samples stored/protected?

###  Data Protection & Backup Plan 

**This week’s assignment is designed to:** **(A)** get you thinking critically about your own data backup and security procedures, and based on that reflection **(B)** prepare a data backup plan (if you already have one you can answer the questions below based on that plan).  **The assignment comes in four parts:**   

1. Sign up for a UF Dropbox allocation: https://cloud.it.ufl.edu/collaboration-tools/dropbox/. If you are not automatically eligible to sign up, your advisor can request that you be granted an allocation: https://cloud.it.ufl.edu/media/clouditufledu/How-to-Obtain-Access-to-UF-Dropbox-for-Education.pdf. 

2. Sign up for a UF Google Suite Allocation: https://cloud.it.ufl.edu/collaboration-tools/g-suite/   

3. Briefly describe how you are adhering to the 3-2-1 backup rule for data related to your thesis. If you are not, describe how you will do so moving forward.  

4.	Using the questions above as a guide, prepare a brief (~1 page max) Data Backup Plan for your thesis research. Include the following information; you can respond with bullet points unless more detailed answers are needed:   

    a.	what needs to be prepared and for how long;
  
    b.	where backups are located;  
    
    c.	who can access backups and how contacted;  
  
    d.	how often data should be backed up;  
    
    e.	what kind of backups are performed;  
  
    f.	who is responsible for performing the backups;  
  
    g.	hardware and software used for performing backups;  
  
    h.	how / how often to check if backups is successful;  
  
    i.	the media are used to backup data;  
  
    j.	a list of any data that are not archived or backed up.
  

### Submission and Grading Rubric

1) Submit the Data Backup Plan document (in either `.txt` or `.pdf` format) via [Canvas](https://elearning.ufl.edu/).  Because of the MLK Holiday, this deadline fopr submission is extended to Wed. 19 Jan at 9 am.

2) Grading Rubric 
    * Assignment completed with thorough answers: 50
    * Most questions answered completely; some require instructor follow-up: 40
    * Many questions missing answers or answers are cursory: 30
    * Instructor follow-up required for homework submission: 20
