---
title: "Week 2: Readings"
author: R package build
date: '2022-01-10'
slug: readings_wk_2
categories:
  - Readings
tags:
  - data storage
  - data security
  - file name conventions
subtitle: ''
summary: ''
authors: []
lastmod: '2022-01-10T11:41:54-05:00'
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
---

## File Formats, Naming Conventions, Data Storage & Security

## Objectives and Competencies for this session:  

  * Describe and implement conventions for proper naming of files 
  * Explain the difference between proprietary and open formats
  * Learn how to efficiently organize their research data files
  * Learn the preferred format for storing and archiving different types of data files
  * Become familiar with different options for cloud data storage and backup 
  * Develop and implement a plan for short- and long-term data storage, back-up, and archiving
  * Learn rules and policies for data security 
  * Become familiar with tools for such tasks as batch renaming of files, cloud data storage, and automated data backup.
  * Explain options for a long-term sustainable preservation strategy/policy for your data (e.g., discipline specific, institutional, departmental, individual).
  * Address the need for conversion to standard formats needed for re-use
  * Perform basic archival processes: checksum, auditing, format migration, etc.
  * Understand costs & time lines for data storage, management tools and services

### Please read / watch these before class:


* **Readings: **

1.  Jan Čurn. 2014. How a bug in Dropbox permanently deleted my 8000 photos.  [[Read Online]](https://medium.com/@jancurn/how-bug-in-dropbox-permanently-deleted-my-8000-photos-cb7dcf13647b) 

2.  PSA: Scrivener, Data Integrity and You. Or, How To Avoid Data Loss Heartbreak.  [[read online]](https://www.reddit.com/r/writing/comments/62hr7o/psa_scrivener_data_integrity_and_you_or_how_to/) 

3. Panzarino, M. 2012. How Pixar’s Toy Story 2 was deleted twice, once by technology and again for its own good. TNW.  [[read online]](https://thenextweb.com/media/2012/05/21/how-pixars-toy-story-2-was-deleted-twice-once-by-technology-and-again-for-its-own-good/)

4.  Hart EM et al. (2016) Ten Simple Rules for Digital Data Storage. PLoS Comput Biol 12(10): e1005097. [[read online]](https://doi.org/10.1371/journal.pcbi.1005097)


* **Videos:** _FYI_: these are last year's versions and I am editing them + adding subtitles. They should be ready by 11 Jan 2021.
 

**Lesson 1: How to Name Your Files**  

<iframe width="560" height="315" src="https://www.youtube.com/embed/BMwI7ubvTnE" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>


**Lesson 2: How to organize Your Files**  

<iframe width="560" height="315" src="https://www.youtube.com/embed/h1hIKNC64ac" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>



**Lesson 3: Data Storage and Backup**

<iframe width="560" height="315" src="https://www.youtube.com/embed/H06GSL66Mec" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

