---
title: 'Week 11: In-Class Work'
# author: "Emilio M. Bruna"
# date: "last update: `r format(Sys.time(), '%d %B %Y')`"
# header-includes:
#    - \usepackage[default]{sourcesanspro}
#    - \usepackage[T1]{fontenc}
mainfont: SourceSansPro
geometry: margin=1in
fontsize: 12pt
linkcolor: blue
urlcolor: blue
output: html_document
  # pdf_document: default
  # html_document:
  #   df_print: paged
  # rmdformats::robobook: default
header-includes:
- \AtBeginDocument{\let\maketitle\relax} # this removes default title section
- \usepackage[default]{sourcesanspro}
- \usepackage{fancyhdr} # modify header into left, center, right
- \pagestyle{fancy} # cues the use of fancy headers
- \fancyfoot{} # cues the use of fancy footer
# month & year on header left
- \fancyhead[L]{`r format(Sys.time(), '%B %Y')`} 
# name and page on header right
- \fancyhead[R]{LAS 6292 Assignment, p. \thepage} 
# - \usepackage{setspace}{singlespace} # manipulate line spacing 
- \usepackage{parskip} # manipulate indents and spacing before/after paragraphs 
- \usepackage{xcolor} # changes colors of text
# to center to top level (#) headings (my name) and change color of font
# more info # https://www.ctan.org/pkg/sectsty
- \usepackage{sectsty} \sectionfont{\centering\color{darkmidnightblue}}
# to center to sub-sub-headings (###) and change color of font
- \usepackage{sectsty} \subsectionfont{\color{darkmidnightblue}}
# http://latexcolor.com/ to choose colors
# define the colors used above with rgb codes
- \definecolor{darkcerulean}{rgb}{0.03, 0.27, 0.49}
- \definecolor{darkmidnightblue}{rgb}{0.0, 0.2, 0.4}
# - \usepackage{ragged2e}
# - \setlength\RaggedRightParindent{15pt}
# - \RaggedRight - # make the right margin ragged
# https://tex.stackexchange.com/questions/258714/prevent-hyphenation-across-lines-enforce-right-margin
# - \hyphenpenalty=10000 #to suppress ordinary hyphenation
# - \exhyphenpenalty=10000 #to prohibit line breaks at explicit hyphens.
# - \setstretch{1.0}

# https://babichmorrowc.github.io/post/changing-fonts-in-rmarkdown-pdfs/

---

<!-- Note: to rendr as pdf delete the \newline -->
<!-- # **LAS 6292 WEEK 2 ASSIGNMENT: Data Storage and Backup**  -->
 
# Transcription & Translation

## Objectives and Competencies:   

  * Understand the different approaches to translation and the research questions for which each is most appropriate
  * Become familiar with software for automated translation via direct upload and api
  * Learn to use the different types of automated and manual transcription tools
  * Understand the strengths and weaknesses of automated translation 
  * Be able to describe the metadata required for transcription files
  
## **Breakout 1:** Translation of Texts into English

1. Download the following .txt files. Note that the link takes you to a page on your browsewr; use "save this page as" to download it to your computer. 

    * [`spanish_text_1voice.txt`](https://raw.githubusercontent.com/BrunaLab/LAS6292_DataManagement/master/static/course-materials/class-sessions/11-transcription-translation/translation_text/spanish_text_1voice.txt)

    * [`turkish_text.txt`](https://raw.githubusercontent.com/BrunaLab/LAS6292_DataManagement/master/static/course-materials/class-sessions/11-transcription-translation/translation_text/turkish_text.txt)

    * [`spanish_text_interview.txt`](https://raw.githubusercontent.com/BrunaLab/LAS6292_DataManagement/master/static/course-materials/class-sessions/11-transcription-translation/translation_text/spanish_text_1voice.txt)

<!-- [`spanish_text_interview.txt`] -->

### STEP 1: Text Translations

Translate the text files with MS Word and Google Docs  

1. Google Docs: [in-doc translation](https://support.google.com/docs/answer/187189?co=GENIE.Platform%3DDesktop&hl=en) (create a new google doc, cut-and-paste the text into the Google Doc, save it, and translate)

2. MS Word: [in-doc translation](https://support.microsoft.com/en-us/topic/translate-text-into-a-different-language-287380e4-a56c-48a1-9977-f2dca89ce93f) 


### STEP 2: Save

Save the translations in your Google Drive in a folder called "class_translations" with the following file names and formats:

1. MS Word: .txt file: `MSWord_[original language]_to_english.txt`  

1. Google: new GoogleDoc: `google_[original language]_to_english`

### STEP 3: Compare

1. Paste the translations into the [Text Comparison Website](https://www.diffchecker.com/diff). Note that you may have to adjust the spacing in the text files to make the text align.  

### STEP 4: Discuss  

1. Are there are any differences in the way key words or concepts were translated? 

2. Are there circumstances under which these could influence the interpretation of the writer's intent? Subtleties of language like formality of tense, tone, or meaning?

3. Do any of them seem "better" or "more accurate"? 


# **Breakout 2:** TRANSCRIPTION 

We will try transcribing audio recorded in different languages using different online services; note that not all languages will be available in all services. 

## STEP 1. Sign up for an account 

Sign up for accounts with the following transcription services. You can cancel the accounts if you think you won't need them afterwards. Additional details and links to tutorials are available on the _Resources_ page.

    * [Otter.ai](https://otter.ai/login)
    
    * [Happy Scribe](https://www.happyscribe.com/)
    
    * [Watson](https://speech-to-text-demo.ng.bluemix.net/); note the "detect multiple speakers" option. 
    
## STEP 2: Transcribe 

1. Download the following audio files. Note that the link takes you to the page where the file is archived; click the 'download' button to save it to your computer.

    * [`turkish_audio.mp3`](https://github.com/BrunaLab/LAS6292_DataManagement/blob/37ebab30eb5744a2a501572cd3b7fc2772009a34/static/course-materials/class-sessions/11-transcription-translation/translation_audio/turkish_audio.mp3)  

    * [`spanish_audio1_voice.mp3`](https://github.com/BrunaLab/LAS6292_DataManagement/blob/master/static/course-materials/class-sessions/11-transcription-translation/translation_audio/spanish_audio_1voice.mp3)  

<!-- 1. `portuguese_audio.mp3`  -->

<!-- indonesian_audio.mp3 -->
<!-- mandarin1_audio.mp3 -->
<!-- mandarin2_audio.mp3 -->
<!-- english_audio.mp3   -->


2. Now transcribe these audio files with each of the different services (note that not all services will transcribe all languages). 

3. Save the resulting transcriptions files as Google Docs or .txt files. Use the following naming convention: `transcription_[language]_[name of service]`  


## STEP 3: Translate

1. Translating these transcriptions to English with Google Docs 

2. Save with the following file names: `translation_[language]_[name of transcription service]` (e.g., `translation_spanish_happyscribe`)  

3. Paste the *translations from transcription* and the *translaiton from the original .txt files* (used in the translation breakout) into the [Text Comparison Website](https://www.diffchecker.com/diff). You may have to adjust the spacing in the text files to make the text align. 

## STEP 4: Discuss

1. Do the transcriptions appear accurate? 

2. What about the translations from transcriptions? Is there a loss in quality when going from audio-to-text-to-English when compared with text-to-English

3. What would be the best approach for research: 

    a. transcribing, editing the transcription, then translating, or 
    b. transcribing, translating, then correcting? 
    
    
    
## Submission

When done please submit via Canvas: 
1) the translations from part 1 (N=12 files),
2) the transcriptions from part 2 (N=2 files), and
3) your responses to the discussion questions

