---
title: "LAS 6292: Text-To-Speech In Class Practice"
date: "updated: `r Sys.Date()`"
header-includes:
   - \usepackage[default]{sourcesanspro}
   - \usepackage[T1]{fontenc}
mainfont: SourceSansPro
geometry: margin=1in
fontsize: 12pt
linkcolor: blue
urlcolor: blue
output:
  pdf_document: default
  html_document:
    df_print: paged
  rmdformats::robobook: default
---


```{r setup, include=FALSE}
library(knitr)
library(rmdformats)

## Global options
options(max.print="75")
opts_chunk$set(echo=FALSE,
	             cache=TRUE,
               prompt=FALSE,
               tidy=TRUE,
               comment=NA,
               message=FALSE,
               warning=FALSE)
opts_knit$set(width=75)
```


###  MS Excel

1. 'Speak Cells' [Tutorial Video](https://youtu.be/5ZOsMe0aPt8). This will allow you to select rows or columns of Excel and have them read back to you. 
        *Alternative video: it's not as thorough, but it is a bit easier to see the menu on [this video](https://youtu.be/q6LOhQThvB8)
speak cells on enter Excel https://youtu.be/DSltR90mkgc

2. 'Speak Cells on Enter': This function will read back what you entered in a cell when you hit "enter". You can set it up using [this tutorial video](https://youtu.be/DSltR90mkgc).


### Google Docs

If you prefer working in Google Docs you can do the same thing. [This article](https://www.businessinsider.com/how-to-make-google-docs-read-to-you) will show you how. You can also watch [this video](https://youtu.be/3UmI5wo5kHg).

In-Class Assignment:

1) Enter 10 rows of data in excel that are typical of the different kinds of data you might be collecting (be sure to give each column a properly formatted name). Try the following:
    * strings (e.g., names of towns or people)
    * numbers
    * codes that are both letters ('AB') and combinations of rows and numbers ('A4', 'B5').
    * leave at least one blank cells in each column. 
    
2) Set up "Speak-Cells" in Excel and have it read back the columns to you. 

3) Summarize the results: did it read the data back accurately? Were you able to understand what it read? How did it deal with the blank cells?

4) Now set up 'Speak Cells on Enter'. Enter some of the data you entered above in some new cells. Now have your partner read some of their data to you.

5) Finally, try entering the text below into a cell in your excel document - the way you would normally - and have Excel read the text back to you. Did it catch any mistakes?

"I closed the door and put the shop key in its usual place behind Francisco's Book on Advanced Principles of Astronomy. Poor Chico. No one has wanted his fat gray book for thirty years. Sometimes I wonder why he keeps teaching even if his students all like other subjects. His mom died when he was very young and moved to Mexico City. He thinks it was his destiny to be a soccer player."

**_When you are done you can submit the brief answers to these questions via canvas as HW 5_**


