---
title: 'LAS 6292: Week 1 - Survey'
author: "Emilio M. Bruna"
date: "`r format(Sys.time(), '%Y')`"
# draft: true # Prevents this from being published if in the posts or pages folder
mainfont: SourceSansPro
geometry: margin=1in
fontsize: 12pt
linkcolor: darkmidnightblue
urlcolor: darkmidnightblue
header-includes:
- \usepackage{fancyhdr}
- \pagestyle{fancy}
- \fancyfoot{}
- \fancyhead[R]{Week 1 Survey, p. \thepage}
- \fancyhead[L]{LAS6292 (`r format(Sys.time(), '%Y')`)}
- \usepackage[default]{sourcesanspro}
- \usepackage{parskip}
- \usepackage{xcolor}
- \AtBeginDocument{\let\maketitle\relax}
- \usepackage{sectsty} \sectionfont{\centering}
- \usepackage{titlesec}
- \usepackage{sectsty} \sectionfont{\centering\color{darkmidnightblue}}
- \usepackage{sectsty} \subsectionfont{\color{darkmidnightblue}}
- \titlespacing{\section}{0pt}{12pt plus 2pt minus 1pt}{0pt plus 1pt minus 1pt}
- \titlespacing{\subsection}{0pt}{12pt plus 2pt minus 1pt}{0pt plus 1pt minus 1pt}
- \titlespacing{\subsubsection}{0pt}{12pt plus 2pt minus 1pt}{0pt plus 1pt minus 1pt}
- \definecolor{darkcerulean}{rgb}{0.03, 0.27, 0.49}
- \definecolor{darkmidnightblue}{rgb}{0.0, 0.2, 0.4}
output: pdf_document
knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile,
  encoding = encoding,
  output_dir = "./instructor-materials/class-sessions/01-intro")
  })
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

<!-- Note: to rendr as pdf delete the  -->
# LAS 6292: WEEK 1 IN-CLASS ASSIGNMENT

&nbsp; 
&nbsp;

### This week's assignment is to briefly answer the following questions. **_If you respond to the Google forms survey there is no need to submit anything via Canvas_**  

&nbsp;
	
This survey has two goals:  

1)	To learn a bit more about your interests and experience so that I can tailor the modify the course content to match the cohort's interests.  

2)	To gather some information the data set(s) you might use for the Data Cleanup Project: one of the goals this semester is to take a “messy” data set, clean it, organize it, and – assuming you have permission and if appropriate at this time – archive it in a repository. This assignment will introduce me to your data set so we can evaluate if it is suitable for the assignment (i.e., is it messy enough, is it big enough?).  The data can be from previous research, even if it is unpublished or not part of a thesis.   

It is important to remember that the 'data set' can be more than one file. For instance, your data set might be four files (or collections of files): (1) A file with the responses to surveys of community members, (2) Census data downloaded from a government website, (3) The transcripts of interviews with key informants, and 
(4) A collection of photographs for ethnographic research.  

Please also remember that you may not have a data set with which to work. That's fine! There are plenty of (useful) data sets out there that are messy and in need of organization. I'll help you find one that matches your interests. 

## Survey Questions

&nbsp;  

1.	UFID Number
   

 
2.	Last Name (as it appears on Canvas) 
   

 
3.	Do you have a name or nickname by which you prefer to be called?
   

 
4.	Canvas has an option for students to list their preferred pronouns. If your preferred pronouns aren't available as an option on Canvas, please feel free to tell me what they are here.
  

 
5.	What degree are you pursuing? 
    * MA/MS
    * PhD
    * Other

6.	What is your department or degree program? 
   

 
7.	Please provide a brief summary - 1 paragraph max - of your research interests.
   

 
8.	Do you have any questions or concerns about the class you'd like to share with me? Perfectly acceptable answers include: "I'm worried about the workload", "I've never taken a bio class", "I'm worried we might have to move on-line in a few weeks because of covid, "I'm worried classes are inperson instead of on-line because of covid", and "None".
   

 
Potential Data Set for Course Project
  

 
9.	Do you have Messy Data you would like to clean up and organize as your course project? This can be data from your current or prior research, including side projects, Master's thesis, undergraduate thesis, etc. *If you don’t have a data set of your own, THAT'S NO PROBLEM - I will help you find one.*

      * Yes
      * No
      * Maybe
     

 
10.	What research question(s) are being addressed with these data?
   

 
11.	What is the status of this data set?Leave only the most relevant answer.*
    * I have finished collecting the data	(Skip to question 13)
    *	I have started data collection but will *not* be done before the semester ends	(Skip to question 13)
    * I have started data collection and *will* be done before the semester ends	(Skip to question 13)
    * Other (please elaborate)	(Skip to question 12)
  

 
### Data Set Status = Other	 
	  

 
12.	If you answered "other" to the previous question, briefly elaborate here.
  

 
### Tell me about the data set(s)
  

 
13.	What are they and what kind of information do they contain?
   

 
14.	What tools and techniques did you use to collect it?
  

 
15.	What format are they in (e.g., sheets of paper, notebooks, spreadsheet, text files, photographs)
   

 
16.	How much data is it? (estimated number of files, surveys, photographs, etc).
   

 
17.	Who collected the data?
    * I did / I am / I will
    * A 3rd party (e.g., my advisor, another student, a collaborator)
    * It it is previously published or public data Other:
   

 
18.	Are the data from research conducted with human subjects?
      * Yes
      * No
  

 
19.	Are any collaborators currently working with the data?
    * Yes
    * No
  

 
20.	Will anyone (e.g., collaborators, advisor) be working with the data in the future?
     * Yes
     * No
     * Don't Know
  

 
21.	What instruments did you use for COLLECTING and RECORDING raw data (check all that apply)

    * paper survey or data recording forms 
    * online surveys
     * notebooks/forms in which personal observations, notes, or responses to questions were recorded
     * audio recordings
     * data from automated data loggers 
     * photographs 
     * video
    * medical instruments (EKG, eye trackers; please elaborate below) 
    * tablets/smartphone
    * Other (elaborate in "Data Collection" section below)


 
22.	What were you gathering on or about? Check all that apply.
    * field-based experiments, observations, or data collection with live animals or plants 
    * museum collections: herbarium specimens, animals (including tissue or blood), fossils 
    * plant or non-human animal tissue or blood (not from a museum specimen).
    * human subjects - behavior, observations, experiments (education, psych, linguistics, etc) 
    * human subjects - tissue, blood, or similar human subjects - records (medical, educational) 
    * museum collections - human remains 
    * museum collections - archeological (pottery, middens mounds) 
    * museum collections - anthropological 
    * museum collections - art (painting, sculpture)
    * Other (elaborate in "Data Collection" section below) 
  

 
### Data collection Instruments & Subjects

 
23.	If you answered "other" to either of the 2 previous questions, please elaborate on the data collection instruments or subjects.
 

 
 
### Instruments

24.	What instruments and software do you use for PROCESSING and ORGANIZING data? Check all that apply
    * MS Word
    * Google Docs
    * Other word processor
    * MS Excel
    * Google Sheets
    * Other spreadsheet software
    * Scrivener
    * OSF
    * Evernote
    * Flickr
    * Text editor
    * Other (elaborate below)
  

 
25.	If you answered "other", please list the other tools you use for PROCESSING and ORGANIZING your research data
 
 
26.	If appropriate for your research domain, do you use any of the following to analyze your data?
 
 
27.	If you answered "other", please list the other tools you use for ANALYZING your research data

 
28.	Are you an R user? NOTE: YOU ARE NOT EXPECTED TO HAVE ANY PROGRAMMING EXPERIENCE TO TAKE THIS CLASS.
 
    * I have never used R
    * Yes - a novice R user
    * Yes - an intermediate R user Yes - an advanced R user
  

 
29.	Will you be gathering data this summer or fall?
    * Yes
    * No
    * Not Sure  

30.	Is there anything you'd like to add? Are there particular topics you'd like to see covered or tools you'd like to learn?




## **Grading Rubric:**  

1. Survey completed with thorough answers: 50  
2. Most questions answered completely; some require instructor follow-up: 40    
3. Many questions missing answers or answers are cursory: 30   
4. Instructor follow-up required for survey submission: 20
