---
title: "Curating Chaos - Session Outlines"
author: "Emilio M. Bruna"
date: "1/7/2021"
output:
  pdf_document: default
  
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

DEFINITELY DO:

Draft DMP submission, which is peerr reviewed by a another (or 2)  student (grade the submission and peer review)

Draft code cleanup submission with peer coding revieww

R studio cloud

### 4. Reproducible data (re)organization  

for next year
1. count the steps exercise -  make a figure or do an analysis, change a variable, and count the number of steps involved.








---
title: "Resources"
author: "Emilio M. Bruna"
date: "1/2/2021"
output: pdf_document
---



# for linguistics
https://onlinelibrary.wiley.com/doi/10.1002/9781444301120.ch3

https://www.cambridge.org/core/journals/bilingualism-language-and-cognition/article/towards-a-credibility-revolution-in-bilingualism-research-open-data-and-materials-as-stepping-stones-to-more-reproducible-and-replicable-research/C4FC0550EE4537D8603942419B288C6E

Linguistics in R
https://benjamins.com/sites/z.195/content/package.html
https://slcladal.github.io/corplingr.html
https://cran.r-project.org/web/packages/languageR/languageR.pdf




# Qualtrix
Importing Qualtrics Data into R
https://www.adrianbruegger.com/post/import-qualtrics-csv-files/


# Class Exercises & Resources

resources from SAGE: https://study.sagepub.com/corti2e + new edition of book https://us.sagepub.com/en-us/nam/managing-and-sharing-research-data/book262873#resources

videos, exercises, etc from Corti book 2nd Edition https://study.sagepub.com/corti2e





# GUIDES: 
Briney KA, Coates H, Goben A (2020) Foundational Practices of Research Data Management. Research Ideas and Outcomes 6: e56508. https://doi.org/10.3897/rio.6.e56508

Goodman A, Pepe A, Blocker AW, Borgman CL, Cranmer K, Crosas M, et al. (2014) Ten Simple Rules for the Care and Feeding of Scientific Data. PLoS Comput Biol 10(4): e1003542. https://doi.org/10.1371/journal.pcbi.1003542

Burley, T.E., and Peine, J.D., 2009, NBII-SAIN Data Management Toolkit, U.S. Geological Survey Open-File Report 2009-1170, 96 p. Available from: http://pubs.usgs.gov/of/2009/1170/

https://www.dcc.ac.uk/guidance
https://wildlife.onlinelibrary.wiley.com/doi/10.1002/wsb.548 


## humanities (general)
*  https://archive.mith.umd.edu/dhcuration-guide/guide.dhcuration.org/legal/policy.html  

## history 
*  https://www.historians.org/jobs-and-professional-development/professional-life/resources-for-graduate-students/graduate-school-from-start-to-finish/aha-guide-to-archival-research
*  https://www.historians.org/publications-and-directories/perspectives-on-history/october-2017/data-management-plans-for-historians-how-to-document-and-protect-your-research
*  https://www.arcgis.com/apps/Cascade/index.html?appid=032048097a7f46f8b3b6859389e18124  


# **Tools**  

## Data Collection, Project Management, & Collaboration
* Data Stewardship Wizard (for DMPs, data management) https://ds-wizard.org/
*  [Open Science Framework](https://osf.io/)  
*  [Open Science Framework (free)](http://tinyurl.com/yaa8hph4)  
*  [Asana (monthly charge)](https://asana.com/)  
*  [Slack](http://tinyurl.com/y9bz8suj)  
*  Ellis, S. E., & Leek, J. T. (2018). How to share data for collaboration. The American Statistician, 72(1), 53-57.  
*  https://www.qsrinternational.com/nvivo-qualitative-data-analysis-software/home  
*  https://atlasti.com/ (nvivo and atlasti about the same purtpiose)  
*  https://zapier.com/pricing   
*  https://www.notion.so/  
*  https://www.devontechnologies.com/apps/devonthink
*  aeon visual timeline software https://www.aeontimeline.com/  
*  IFTT: https://ifttt.com/   
*  fiji: https://fiji.sc/ image processing anal;ysis  
*  https://www.taguette.org/ qualitative data research tool, all fields, exportable looks good  
*  scanning apps:  https://www.nytimes.com/wirecutter/reviews/best-mobile-scanning-apps/  
*  https://www.literatureandlatte.com/scrivener/overview  
* https://www.pinterest.com/ahahistorians/a-digital-tool-box-for-historians/

## Data Security

*  [UF Library Guidelines for Data Security](http://guides.uflib.ufl.edu/datamanagement/security)  
*  UF Office of Information Security and Compliance  
*  [Cyber Safeguards for UF](https://security.ufl.edu/wp-content/uploads/2012/12/data-security-handouts.pdf)  
*  [UF IT Information Security](https://security.ufl.edu/learn-information-security/protect-yourself/data/)  
*  [UF IRB )Data Record Storage and Security](http://irb.ufl.edu/index/data/1981-2.html)   
*  [UF Data Classification Policy](https://it.ufl.edu/policies/information-security/data-classification-policy/)   
*  [UF Office of Information Security and Compliance Cyber Safeguards for UF](https://security.ufl.edu/wp-content/uploads/2012/12/data-security-handouts.pdf)  
*  [data anonymizing is hard](https://onezero.medium.com/why-anonymized-data-isn-t-so-anonymous-535d2db75a2d)   

*  [Uploading](http://tinyurl.com/y9bz8suj)  

DataONE Best Practices Working Group, DataONE  (July 01, 2010) "Best Practice: Ensure integrity and accessibility when making backups of data". Accessed through the Data Management Skillbuilding Hub. [[read online]]( https://dataoneorg.github.io/Education/bestpractices/ensure-integrity-and) [download pdf]



## **Week 14: Data Sharing, Reuse, & Archives**  

*  https://www.authorea.com/users/260319/articles/436166-research-data-repositories-chosen-by-researchers-across-broad-range-of-disciplines-from-an-analysis-of-145-000-data-availability-statements?commit=05d5052a56e7ac63dd07d17fb88c47430b194874  

* read from [IPUMS](https://usa.ipums.org/usa/tutorials.shtml) directly into R with [this package](https://cran.r-project.org/web/packages/ipumsr/vignettes/ipums.html#:~:text=The%20ipumsr%20package%20allows%20you,integrated%20across%20time%20and%20space).

huge list of archives: https://www.nature.com/sdata/policies/repositories 
*  [Qualitative Data Repository](https://qdr.syr.edu/)  
*  [google Dataset Search](https://datasetsearch.research.google.com/) and [explanatory blog post](https://blog.google/products/search/discovering-millions-datasets-web/)
*  [Cessda](https://www.cessda.eu/)
SMP


* Gregory K, Khalsa SJ, Michener WK, Psomopoulos FE, de Waard A, Wu M (2018) Eleven quick tips for finding research data. PLoS Comput Biol 14(4): e1006038. https://doi.org/10.1371/journal.pcbi.1006038

*  Sielemann K, Hafner A, Pucker B. 2020. The reuse of public datasets in the life sciences: potential risks and rewards. PeerJ 8:e9954 https://doi.org/10.7717/peerj.9954  
*  Mauthner, N. S., & Parry, O. (2009). Qualitative data preservation and sharing in the social sciences: On whose philosophical terms?. Australian Journal of Social Issues, 44(3), 291-307.  
*  Baker, K. S., & Duerr, R. E. (2017). Research and the changing nature of data repositories. Curating Research Data, 33.
*  Whyte, A. & Wilson, A. (2010). How to Appraise and Select Research Data for Curation. DCC How-to Guides. Edinburgh: Digital Curation Centre. (also available online: http://www.dcc.ac.uk/resources/how-guides)  
*  UF Library Guide: http://guides.uflib.ufl.edu/datamanagement/sharing
*  Bruna, E. M. 2010. Journals can advance tropical biology and conservation by requiring data archiving.  Biotropica 42(4): 399–401  
*  Piwowar, H. A., & Vision, T. J. (2013). Data reuse and the open data citation advantage. PeerJ, 1, e175.    
*  Michener WK. 2015. Ecological data sharing. Ecological Informatics. 2015 Sep 1;29:33-44.    
*  Participants _want_ their data shared: https://onlinelibrary.wiley.com/doi/abs/10.1002/eahr.500044   



