---
title: "Metadata Descriptors for Ecological Data (Table 1 in Michener et al. 1997)"
date: "updated: `r Sys.Date()`"
header-includes:
- \AtBeginDocument{\let\maketitle\relax} # this removes default title section
- \usepackage[default]{sourcesanspro}
- \usepackage{fancyhdr} # modify header into left, center, right
- \pagestyle{fancy} # cues the use of fancy headers
- \fancyfoot{} # cues the use of fancy footer
# header left
- \fancyhead[L]{Ecological Metadata} 
# header right
- \fancyhead[R]{p. \thepage} 
- \fancyfoot[R]{Last update `r format(Sys.time(), '%d %B %Y')`}
# - \usepackage{setspace}{singlespace} # manipulate line spacing 
- \usepackage{parskip} # manipulate indents and spacing before/after paragra phs 
- \usepackage{xcolor} # changes colors of text
# to center to top level (#) headings (my name) and change color of font
# more info # https://www.ctan.org/pkg/sectsty
- \usepackage{sectsty} \sectionfont{\centering\color{darkmidnightblue}}
# to center to sub-sub-headings (###) and change color of font
- \usepackage{sectsty} \subsectionfont{\color{darkmidnightblue}}
# http://latexcolor.com/ to choose colors
# define the colors used above with rgb codes
- \definecolor{darkcerulean}{rgb}{0.03, 0.27, 0.49}
- \definecolor{darkmidnightblue}{rgb}{0.0, 0.2, 0.4}
mainfont: SourceSansPro
geometry: margin=1in
fontsize: 12pt
linkcolor: blue
urlcolor: blue
output:
  pdf_document: default
  # html_document:
  #   df_print: paged
  # rmdformats::robobook: default
---

"Important Metadata Elements" (Source: p. 32 of "ICPSR Guide to Social Science Data Preparation and Archiving: Best Practice Throughout the Data Life Cycle (6th Edition)". [download link](https://www.icpsr.umich.edu/web/pages/deposit/guide/)


**A. Data Collection and File Creation:** 

A list of the most important items to include in social science metadata is presented below. Note that many of the high-level elements have counterparts in the Dublin Core Metadata Initiative (DCMI) element set. The DCMI is a standard aimed at making it easier to describe and to find resources using the Internet. For more information on the DCMI, please view their website at www.dublincore.org.

1. Principal investigator(s) [Dublin Core -- Creator]. Principal investigator name(s), and affiliation(s) at the time of data collection.

2. Title [Dublin Core -- Title]. Official title of the data collection.

3. Funding sources. Names of funders, including grant numbers and related acknowledgments.

4. Data collector/producer. Persons or organizations responsible for data collection, and the date
and location of data production.

5. Project description [Dublin Core -- Description]. A description of the project, its intellectual goals, and how the data articulate with related datasets. Publications providing essential information about the project should be cited. A brief project history detailing any major difficulties faced or decisions made in the course of the project is useful.

6. Sample and sampling procedures. A description of the target population investigated and the methods used to sample it (assuming the entire population is not studied). The discussion of the sampling procedure should indicate whether standard errors based on simple random sampling are appropriate, or if more complex methods are required. If weights were created, they should be described. If available, a copy of the original sampling plan should be included as an appendix. A clear indication of the response rate should be provided, indicating the proportion of those sampled who actually participated in the study. For longitudinal studies, the retention rate across studies should also be noted.

7. Weighting. If weights are present, information should be provided on weight variables, how they were constructed, and how they should be used.

8. Substantive, temporal, and geographic coverage of the data collection [Dublin Core Coverage]: Descriptions of topics covered, as well as the time period, and the geographic location. 

9. Data source(s) [Dublin Core -- Source]. If a dataset draws on resources other than surveys, citations to the original sources or documents from which the data were obtained. 

10. Unit(s) of analysis/observation. A description of who or what is being studied.

11. Variables. For each variable, the following information should be provided:

11a. The exact question wording or the exact meaning of the datum. Sources should be cited for questions drawn from previous surveys or published work.

11b. The text of the question integrated into the variable text. If this is not possible, it is useful to have the item or questionnaire number (e.g., Question 3a), so that the archive can make the necessary linkages.

11c. Universe information, i.e., who was actually asked the question. Documentation should indicate exactly who was asked and was not asked the question. If a filter or skip pattern indicates that data on the variable were not obtained for all respondents, that information should appear together with other documentation for that variable.

11d. Exact meaning of codes. The documentation should show the interpretation of the
codes assigned to each variable. For some variables, such as occupation or industry, this information might appear in an appendix.

11e. Missing data codes. Codes assigned to represent data that are missing. Such codes typically fall outside of the range of valid values. Different types of missing data should have distinct codes.

11f. Unweighted frequency distribution or summary statistics. These distributions should show both valid and missing cases.

11g. Imputation and editing information. Documentation should identify data that have been estimated or extensively edited.

11h. Details on constructed and weight variables. Datasets often include variables
constructed using other variables. Documentation should include “audit trails” for
such variables, indicating exactly how they were constructed, what decisions were
made about imputations, and the like. Ideally, documentation would include the exact programming statements used to construct such variables. Detailed information on the construction of weights should also be provided.

11i. Location in the data file. For raw data files, documentation should provide the field or column location and the record number (if there is more than one record per case). If a dataset is in a software-specific system format, location is not important, but the order of the variables is. Ordinarily, the order of variables in the documentation will be the same as in the file; if not, the position of the variable within the file must be indicated.

11j. Variable groupings. Particularly for large datasets, it is useful to categorize variables into conceptual groupings.

12. Related publications. Citations to publications based on the data, by the principal investigators or others. 

13. Technical information on files. Information on file formats, file linking, and similar information. 

14. Data collection instruments. Copies of the original data collection forms and instruments. Other researchers often want to know the context in which a particular question was asked, and it is helpful to see the survey instrument as a whole. Copyrighted survey questions should be acknowledged with a citation so that users may access and give credit to the original survey and its author.

15. Flowchart of the data collection instrument. A graphical guide to the data, showing which respondents were asked which questions and how various items link to each other. This is particularly useful for complex questionnaires or when no hard copy questionnaire is available.

16. Index or table of contents. A list of variables either in alphabetic order or organized into variable groups with corresponding page numbers or links to the variables in the technical documentation or codebook.

17. List of abbreviations and other conventions. Variable names and variable labels often contain abbreviations. Ideally, these should be standardized and described.
Interviewer guide. Details on how interviews were administered, including probes, interviewer specifications, use of visual aids such as hand cards, and the like.

18. Coding information. A document that details the rules and definitions used for coding the data. This is particularly useful when open-ended responses are coded into quantitative data and the codes are not provided on the original data collection instrument, or for variables that are derived or constructed using the data that were originally collected. 


**B. Readme.txt Files.** 

Technical documentation is important to facilitate data archiving, curation, and re-use, but sometimes researchers need more information than a codebook provides. README files supplement codebooks and DDI metadata by providing nonstandard documentation to researchers. A README file is a plain-text document that makes research data easier to navigate and use, and is stored alongside data. README files originated in computer science where software developers frequently create and navigate complex directory structures with hundreds or thousands of files.  

The name README implies that a file should be read by researchers before they begin using a dataset. README files are always saved in .txt format, which means that they are nonproprietary. Generally, README files contain high level, descriptive information summarizing the contents of a dataset and provide documentation describing its organization. Most README files do not have a defined structure, but a commonality is that they allow data users to understand the purpose and organization of a dataset once they read the file. README files are also useful in adding clarity to questions about subfolder organization.