---
title: "Week 3: Pre-Class Announcement"
date: "updated: `r Sys.Date()`"
header-includes:
   - \usepackage[default]{sourcesanspro}
   - \usepackage[T1]{fontenc}
mainfont: SourceSansPro
geometry: margin=1in
fontsize: 12pt
linkcolor: blue
urlcolor: blue
output:
  pdf_document: default
  html_document:
    df_print: paged
  rmdformats::robobook: default
---

```{r setup, include=FALSE}
library(knitr)
library(rmdformats)

## Global options
options(max.print="75")
opts_chunk$set(echo=FALSE,
	             cache=TRUE,
               prompt=FALSE,
               tidy=TRUE,
               comment=NA,
               message=FALSE,
               warning=FALSE)
opts_knit$set(width=75)
```



Hi all, a couple of things to do before Friday:

## For class this week:
1. Please bring **your computer**. If you need to borrow a laptop or get access to a computer let me know.
    
2. You will need a **spreadsheet program** such as MS Excel or LibreOffice. You can use the program of your choice, but the exercises are optimized for MS Excel. If you don't want to install Excel, UF students can use the online version for free For more information on how to accessing Excel online watch [this tutorial video](https://datacarpentry.org/semester-biology/lessons/SQL-data/).

3. **Reading:** don't forget to do the reading, *especially* the paper by Broman and Woo on how to organize data in spreadsheets. It may well be one of the more helpful papers you read as a grad student...really.
## It is also time to install two pieces of software to make sure they are ready for Week 4:  
    
1. **the R programming language**: You can download the version of R for your computer operating system [here](https://cran.rstudio.com/); it's free.
    
    * **_For Mac computers_** click on 'Download R for (Mac) OS X', then chose the version of R for your operating system, i.e., macOS 10.13 (High Sierra), OS X 10.11 (El Capitan), Mac OS X 10.9 (Mavericks), etc.
    * **_For PC computers_**: click on Download R for Windows, then click 'base' or 'install R for the first time'.
    * **_For Linux_**: click on 'Download R for Linux'; after which you are on your own. Then again you use Linux, so you probably don't need my help anyway.
     * **_If you need help:_** watch [this video tutorial](https://www.linkedin.com/learning/learning-r-2/installing-r?u=41282748) or contact me. _Note that the tutorial requires you be a UF affiliate and either on campus or logged to the UF network via VPN_. 
        
2. **RStudio**: the software used to work with R. There are other 'environments' one can use for R programming, but RStudio is by far the most widely used and useful. 

    * We use the 'Free Open-Source Desktop Version', which [you can download here](https://rstudio.com/products/rstudio/download/#download). Choose the version for your computer operating system and install as you would any other software. 
    * **If you need help**: watch [this video tutorial](https://www.linkedin.com/learning/learning-r-2/installing-rstudio?u=41282748) or contact me. _Note that the tutorial requires you be a UF affiliate and either on campus or logged to the UF network via VPN_. 
    
3. **Verify the installation** by opening RStudio to see if it opens properly. If you are really motivated, you can also install the `Tidyverse` library by starting RStudio and at the console typing `install.packages("tidyverse")`.
    

