---
title: "DMP Assignment"
author: "Emilio M. Bruna"
date: "1/4/2021"
output:
  pdf_document: default
  html_document: default
---
### **ASSIGNMENT:** DATA MANAGEMENT PLAN  
### **DUE DATE:** The DMP is due DATE and is worth XXXX points.   
### **SUBMISSION:** Submit a copy (in txt or MS Word format) via the course e-learning website. 

As we learned in class, a Data Management Plan (DMP) is a critical document that describes the data to be collected, how it will be stored, secured, and managed, and who has responsibility for it. Indeed, one sign of its importance is that many funding agencies, including NSF and NIH, require a DMP with all grant applications. 

**Your assignment is to prepare a DMP for your thesis data. **This plan can be for the data you have already collected or data you will be collecting this summer – the choice is yours (come find me to discuss if you have any questions or want to discuss the options). The DMP is to be prepared using the DMP Tool: https://dmptool.org/help; you can use the template that is best suited to your research. 




#### GUIDELINES

Not all DMPs include the same information; below are some of the topics you could consider including as well as some additional resources to which you can refer. 

1.	Project, experiment, and data description  
      
      * What’s the purpose of the research?
      * What is the data? How and in what format will the data be collected? Is it numerical data, image data, text sequences, or modeling data?
      * How much data will be generated for this research?
      * How long will the data be collected and how often will it change?
      * Are you using data that someone else produced? If so, where is it from?
      * Who is responsible for managing the data? Who will ensure that the data management plan is carried out?

2.	Documentation, organization, and storage  

      * What documentation will you be creating in order to make the data understandable by other researchers?
      * Are you using metadata that is standard to your field? How will the metadata be managed and stored?
      * What file formats will be used? Do these formats conform to an open standard and/or are they proprietary?
      * Are you using a file format that is standard to your field? If not, how will you document the alternative you are using?
      * What directory and file naming convention will be used?
      * What are your local storage and backup procedures? Will this data require secure storage?
      * What tools or software are required to read or view the data?

3.	Access, sharing, and re-use  

      * Who has the right to manage this data? Is it the responsibility of the PI, student, lab, University, or funding agency?
      * What data will be shared, when, and how?
      * Does sharing the data raise privacy, ethical, or confidentiality concerns?  Do you have a plan to protect or anonymize data, if needed?
      * Who holds intellectual property rights for the data and other information created by the project? Will any copyrighted or licensed material be used? Do you have permission to use/disseminate this material?
      * Are there any patent- or technology-licensing-related restrictions on data sharing associated with this grant? The Universities technology licensing office can provide this information.
      * Will this research be published in a journal that requires the underlying data to accompany articles?
      * Will there be any embargoes on the data?
      * Will you permit re-use, redistribution, or the creation of new tools, services, data sets, or products (derivatives)? Will commercial use be allowed?

4.	Archiving  

      * How will you be archiving the data? Will you be storing it in an archive or repository for long-term access? If not, how will you preserve access to the data?
      * Is a discipline-specific repository available? If not, you could consider depositing your data into the UF Institutional Repository 
      * How will you prepare data for preservation or data sharing? Will the data need to be anonymized or converted to more stable file formats?
      * Are software or tools needed to use the data? Will these be archived?
      * How long should the data be retained? 3-5 years, 10 years, or forever?  


#### Resources for Creating DMPs  

* Guidelines for Effective Data Management Plans and Data Management Plan Resources and Examples (ICPSR): Framework for creating a plan and links to examples of data management plans in various scientific disciplines  
* UF Library Guidelines: http://guides.uflib.ufl.edu/datamanagement/dmp  
* DMP Tool: https://dmptool.org/help  


