---
title: "metadata assignment"
author: "Emilio M. Bruna"
date: "1/4/2021"
output:
  pdf_document: default
  html_document: default
---
### **ASSIGNMENT:** Metadata
### **DUE DATE:** The assignment is due DATE and is worth XXXX points  
### **SUBMISSION:** Submit a copy (in txt or MS Word format) via the course e-learning website. 

One of the goals this semester is to take a “messy” dataset, clean it, and organize it. As we discussed in class, however, a dataset is only as useful as the metadata that accompanies it. This assignment is the opportunity to prepare the metadata that will accompany your dataset and the get feedback on it from me and other potential users (your classmates). 

**For this assignment you need to prepare the following: **

1)	A metadata file with all the information required to interpret your data (more on that below). You can submit this as an MS Word Document if you wish – track changes mode can make it easier to see and accept suggested edits – but I will accept .txt documents, links to Google word documents, access to .Rmd files so I can make suggested changes via pull requests, or any other format that that you prefer. 

The metadata that need to be included depend on the project and dataset (e.g., if you are doing online surveys you obviously don’t have to include info about topography or local habitats), so in your file assignment you should include the most relevant subheadings from the five classes of Data Descriptors in Table 1 of Michener et al 1997: 

1)	General Information about the project (Class 1)
2)	Detailed information on how, when, and where data were collected (Class 2)
3)	Information on dataset’s status an accessibility (Class  3)
4)	Information on the dataset’s organization and how values are to be interpreted (Class 4
5)	Supplemental Descriptors (Class 5)

You can get a text version of the categories and subheadings found in Table 1 at https://github.com/embruna/Michener_etal_Table1 so you don’t have to re-enter them manually. 

**Please submit the assignment via e-learning. You can either:**

1)	upload the file OR
2)


#### RUBRIC



