---
title: "data archiving"
author: "Emilio M. Bruna"
date: "2023-02-06"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


### 14. Data Sharing, Reuse, & Archives   
*understand advantages of data sharing and archiving
*discuss concerns and and obstacles related to data sharing
*understand restrictions on reuse of data, software, and instrumentation, including different CCO and Public Domain licences)
*adress reuse / sgharing requiorements from granting aqgencies or sponsors

*understand options for maximizing data reuse
*understand data identifiers and what they are for
* underrstand benefits of using unique researcher id in metadata

*	Identify types of available repositories/archives (discipline-based, institutional, etc.)
*	Chooses appropriate option for long-term storage of data
*	Understand process issues for depositing data in repository


* **Intro Material (lecture/videos): **
  * https://dataoneorg.github.io/Education/lessons/02_datasharing/L02_Exercise.pdf
  * https://dataoneorg.github.io/Education/lessons/08_citation/index
  * https://dataoneorg.github.io/Education/bp_step/discover/

* **In-class Exercise:**  Find data, look at data archive and see if they can understand it



Original Readings for this week: 

1.  Alexander, S.M., Jones, K., Bennett, N.J. et al. Qualitative data sharing and synthesis for sustainability science. Nat Sustain 3, 81–88 (2020).  
        [[read online]](https://doi.org/10.1038/s41893-019-0434-8 )  [[download pdf]](https://github.com/BrunaLab/LAS6292_DataManagement/blob/master/instructor-materials/readings/Alexander_etal_2019_NatureSustainability.pdf)

2. Renaut, S. et al. 2018. Management, Archiving, and Sharing for Biologists and the Role of Research Institutions in the Technology-Oriented Age. *BioScience* 68(6)400–411  
        [[read online]](https://academic.oup.com/bioscience/article/68/6/400/4983937) [[download pdf]](https://github.com/BrunaLab/LAS6292_DataManagement/blob/master/instructor-materials/readings/Renaut_etal_2018_Bioscience.pdf)  

2.  Duke, Clifford S., and John H. Porter. 2013. "The ethics of data sharing and reuse in biology." BioScience 63(6): 483-489.  
        [[read online]](https://academic.oup.com/bioscience/article/63/6/483/226339) [[download pdf]](https://github.com/BrunaLab/LAS6292_DataManagement/blob/master/instructor-materials/readings/Duke%26Porter_2013.pdf)

3.  Tenopir, C., et al.  (2015). Changes in data sharing and data reuse practices and perceptions among scientists worldwide. PloS one, 10(8), e0134826.  
        [[read online]](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0134826) [[download pdf]](https://github.com/BrunaLab/LAS6292_DataManagement/blob/master/instructor-materials/readings/Tenopir_etal_2015.PDF)

4.  Mauthner, NS, & O. Parry O. 2009. Qualitative data preservation and sharing in the social sciences: On whose philosophical terms?. Australian J of Social Issues 44(3):291-307.  
         [[read online]](https://onlinelibrary.wiley.com/doi/abs/10.1002/j.1839-4655.2009.tb00147.x)  [[download pdf]](https://github.com/BrunaLab/LAS6292_DataManagement/blob/master/instructor-materials/readings/Mauthner_et_al-2009-Australian_Journal_of_Social_Issues.pdf)
