---
title: "LAS 6292: DMPs"
date: "updated: `r Sys.Date()`"
header-includes:
- \AtBeginDocument{\let\maketitle\relax} # this removes default title section
- \usepackage[default]{sourcesanspro}
- \usepackage{fancyhdr} # modify header into left, center, right
- \pagestyle{fancy} # cues the use of fancy headers
- \fancyfoot{} # cues the use of fancy footer
# month & year on header left
- \fancyhead[L]{LAS 6292 Spring `r format(Sys.time(), '%Y')`, EM Bruna} 
# name and page on header right
- \fancyhead[R]{Data Management Plans, p. \thepage} 
- \fancyfoot[R]{Last update `r format(Sys.time(), '%d %B %Y')`}
# - \usepackage{setspace}{singlespace} # manipulate line spacing 
- \usepackage{parskip} # manipulate indents and spacing before/after paragra phs 
- \usepackage{xcolor} # changes colors of text
# to center to top level (#) headings (my name) and change color of font
# more info # https://www.ctan.org/pkg/sectsty
- \usepackage{sectsty} \sectionfont{\centering\color{darkmidnightblue}}
# to center to sub-sub-headings (###) and change color of font
- \usepackage{sectsty} \subsectionfont{\color{darkmidnightblue}}
# http://latexcolor.com/ to choose colors
# define the colors used above with rgb codes
- \definecolor{darkcerulean}{rgb}{0.03, 0.27, 0.49}
- \definecolor{darkmidnightblue}{rgb}{0.0, 0.2, 0.4}
# - \usepackage{ragged2e}
# - \setlength\RaggedRightParindent{15pt}
# - \RaggedRight - # make the right margin ragged
# https://tex.stackexchange.com/questions/258714/prevent-hyphenation-across-lines-enforce-right-margin
# - \hyphenpenalty=10000 #to suppress ordinary hyphenation
# - \exhyphenpenalty=10000 #to prohibit line breaks at explicit hyphens.
# - \setstretch{1.0}

# https://babichmorrowc.github.io/post/changing-fonts-in-rmarkdown-pdfs/

mainfont: SourceSansPro
geometry: margin=1in
fontsize: 12pt
linkcolor: blue
urlcolor: blue
output: pdf_document
knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile, 
  encoding = encoding, 
  output_dir = "./static/uploads/notes")
  })

---


```{r setup, include=FALSE}
library(knitr)
library(rmdformats)

## Global options
options(max.print="75")
opts_chunk$set(echo=FALSE,
	             cache=TRUE,
               prompt=FALSE,
               tidy=TRUE,
               comment=NA,
               message=FALSE,
               warning=FALSE)
opts_knit$set(width=75)
```




<!-- ### 8. Data Management Plans    -->
<!-- * **Intro Material (lecture/videos): ** -->
<!--   * https://dataoneorg.github.io/Education/lessons/03_planning/index  -->
<!--   * https://dataoneorg.github.io/Education/bp_step/integrate/ -->

<!-- * **In-class Exercise:** DMP tool to start buildling their own DMP     -->


# Resources for DMPs

## Some sample DMPs

1. DataOneDMP samples for NSF

* NSF General: [Mauna Loa example](https://github.com/BrunaLab/LAS6292_DataManagement/blob/master/instructor-materials/class-sessions/09-DMP/example_dmps/DMP_MaunaLoa_Formatted.pdf)
* NSF General: [Rio Grande example](https://github.com/BrunaLab/LAS6292_DataManagement/blob/master/instructor-materials/class-sessions/09-DMP/example_dmps/Repository%20selection%20exercise%20Data%20One%20Geosciences%20DMP.pdf)
* NSF DEB: [Emilio Bruna Heliconia example](https://github.com/BrunaLab/LAS6292_DataManagement/blob/master/instructor-materials/class-sessions/09-DMP/example_dmps/DataManagementPlan.pdf)

2. Sample DMPs on the 'DMP Tool' website [Public DMPs](https://dmptool.org/public_plans) **(_note: "Public DMPs are plans created using the dmptool service and shared publicly by their owners. They are not vetted for quality, completeness, or adherence to funder guidelines."_)**

3. National Endowment for the Humanities: Data Management Plans From Successful Grant Applications (2015-2018) and (2011 - 2014) can be found as downloadable zip files [on this page](https://www.neh.gov/about/foia/library)

4. A *really* nice [DMP for a Digital Humanities Project](https://guides.library.ucla.edu/c.php?g=180580&p=1189056) by researchers at the University of Maryland, College Park.

# Additional resources to help prepare your DMP 

1. Qualitative Data have some unique issues regarding their description and storage, so the [Qualitative Data Archive](https://qdr.syr.edu/guidance/managing/dmp-checklist) has put together a great checklist of things to consider. 

2. [Short Checklist & Questions to Consider](https://www.dcc.ac.uk/sites/default/files/documents/resource/DMP/DMP_Checklist_2013.pdf) when putting together a DMP

3. [Very in-depth Checklist & Questions to Consider](https://dmptool.org/general_guidance) when putting together a DMP

4. [UF Library Guidelines](http://guides.uflib.ufl.edu/datamanagement/dmp) for preparing a DMP

5. Another tools for creating DMPs is the [DMP Online](dmponline.dcc.ac.uk)

# **Reminder: What is a DMP?**

* Formal document that lays out your plan for managing the data you will collect (or have collected). 
* Outlines what you will do with your data during and after you complete your research
* Ensures your data is safe for the present and the future
* [Video overview](https://www.youtube.com/watch?v=fcCj6sNvoOw) by RWTH Aachen University (12 min).

## **Why do one?**  

* Save time
* Less reorganization later
* Increase research efficiency
* Makes it easier to archive data downt he road (some data centers and repositories have specific requirements for data documentation, and knowing these requirements in advance saves time and effort that might be spent trying to correct data after they are collected).
* Increasingly: you don't have a choice. Many funding agencies (e.g., NSF, NIH, NEH) now require a DMP for proposal submission.

## **What are the components of a DMP?**  

1. Information about data & data format
2. Metadata content and format
3. Policies for access, sharing and re-use
4. Long-term storage and data management
5. Roles and responsibilities
6. Budget 

*Some funders or institutions may require specific elements in a data management plan; you should check in advance to make sure you meet all requirements*

### **1. Information About Data & Data Format**  

#### *1.1  Description of data to be produced*  

* Experimental
* Observational
* Raw or derived
* Physical collections
* Models and their outputs
* Simulation outputs
* Curriculum materials
* Software
* Images
* Other 

#### *1.2  How data will be acquired?*  

* When? Where? Method?

#### *1.3  How data will be processed*  

* Software used
* Algorithms
* Workflows
* Data transformations/formats needed (Consider archive policies)

* *This step is important to consider before the project since it may affect how data are organized, what formats are used, and how much should be budgeted for hardware and software. Things to consider are what software may be used, what algorithms will be employed, how these fit into the overall workflow of the project.*

#### *1.4  File formats*  

* Justification
* Naming conventions

#### *1.5 Quality assurance & control during sample  collection, analysis, and processing*  

#### *1.6  Existing data*  

* If existing data are used, what are their origins?
* Will your data be combined with existing data?
* What is the relationship between your data and existing data?

#### *1.7 How data will be managed in short-term*  

* Version control
* Backing up
* Security & protection
* Who will be responsible


### **2. Metadata Content & Format**  

* Metadata defined: 
* Documentation and reporting of data
* Contextual details: Critical information about the dataset
* Information important for using the data
* Descriptions of temporal and spatial details, instruments, parameters, units, files, etc. 

#### *2.1 What metadata are needed*  

* Details that make data meaningful

#### *2.2 How metadata will be created and/or captured*  

* Lab notebooks? GPS units? Auto-saved on instrument?

#### *2.3 What format will be used for the metadata*  

* Standards for community
* Justification for format chosen


### **3. Policies for Access, Sharing, Reuse**

#### *3.1  Obligations for sharing*  

* Funding agency
* Institution
* Other organization
* Legal

#### *3.2  Details of data sharing*

* How long?
* When? 
* How access can be gained?
* Data collector rights

#### *3.2  Ethical/privacy issues with data sharing*

#### *3.3  Intellectual property & copyright issues*

* Who owns the copyright? (? Institutions and/or funding agencies often have a policy for intellectual property and copyright. There may be other considerations such as embargos on data due to patents, politics, or journal requirements.)
* Institutional policies
* Funding agency policies
* Embargos for political/commercial reasons

#### *3.4  Intended future uses/users for data*

* This helps determine the most appropriate data center to archive your data.

#### *3.5  Citation*

* How should data be cited when used?
* Do you need a persistent citation (e.g. DOI)?

### **4. Long-term Storage & Data Management**

#### *4.1  What data will be preserved*
#### *4.2  Where will it be archived*

* Most appropriate archive for data
* Community standards

#### *4.4   Who will be responsible*

* Contact person for archive


### **5. Roles and responsibilities**

#### *5.1 Outline the roles and responsibilities for implementing this data management plan*.

* Who will be responsible for data management and for monitoring the data management plan? How will adherence to this data management plan be checked or demonstrated? What process is in place for transferring responsibility for the data? Who will have responsibility over time for decisions about the data once the original personnel are no longer available?

### **6. Budget**

#### *6.1  Anticipated costs*

* Time for data preparation & documentation
* Hardware/software for data preparation & documentation
* Personnel
* Archive costs

#### *6.2  How costs will be paid*

## NSF DMP Requirements

**From Grant Proposal Guidelines:** "Plans for data management and sharing of the products of research. Proposals must include a supplementary document of no more than two pages labeled “Data Management Plan”. This supplement should describe how the proposal will conform to NSF policy on the dissemination and sharing of research results, and may include: the types of data, samples, physical collections, software, curriculum materials, and other materials to be produced in the course of the project the standards to be used for data and metadata format and content (where existing standards are absent or deemed inadequate, this should be documented along with any proposed solutions or remedies) policies for access and sharing including provisions for appropriate protection of privacy, confidentiality, security, intellectual property, or other rights or requirements policies and provisions for re-use, re-distribution, and the production of derivatives plans for archiving data, samples, and other research products, and for preservation of access to them."

## *REMINDER*

The key components of a DMP:  

* Information about data & data format
* Metadata content and format
* Policies for access, sharing and re-use
* Long-term storage and data management
* Budget
