---
title: "Spring 2021 Feels"
author: "Emilio M. Bruna"
date: "1/7/2021"
output: html_document
---

**A quick word about the upcoming Spring 2021 Semester**
Hello everyone, 

Like you I was optimistic all of this would be behind us by the start of this semester, but here we are. I'm guessing that you are also feeling tired, frustrated, and a bit zoomed-out.  Plus just when we were figuring out how to do all of our classes in a fully asynchronous style, the the university threw "HyFlex" at us, meaning some of you will be in class and the rest will be participating remotely.   I hope you will be patient with me - and with each other - as we learn to navigate this new-new way of learning together. 

In the meantime, I wanted you to know a few things: 

1) Class will be meeting on Friday. There are no assignments or reading that need to be done in advance of the session. 

2) The in-person section will meet in 376 Grinter Hall. If you are registered for the in-person section but prefer to participate online - for whatever reason - you may do so. Your health and safety are my first priority.

3) The zoom link for class can be found on the class page. It is the same for all class sessions AND my office hours. If you have any problems logging on you can send me a message.

4) The fact that we've been doing this since March doesn't mean it's gotten easier or less stressful. In fact, I feel like it's the opposite - in my house we continue to operate on what we call "Survival Mode".  If you have to miss class, or need extra time to complete work, or just need some time away - no problem, no explanation needed. Just let me know and if I can help in any way. Along those lines...

5) I'm working to make the class as "flipped" as possible. After the first session, most of the remaining weeks will have the following format:

a) Before class: videos and reading introducing the topic for the week

b) During Class: hands-on work and in-class exercises to apply the lessons learned (with submission of some materials for me to review)

c) After class: finish any exercises not completed during class time, prepare for next session.

6) Once in a while there might be some short lectures to better cover challenging material, and there are a few days where we will have a class discussion of the reading.

7) I've tried to keep the time commitments, reading, and assignments to a minimum.  The "weekly assignments" are actually designed to be completed during the class session.

8) To ensure any students that miss class can take advantage of any in-class discussions or presentations I will be recording the zoom sessions. If you don't want to appear in the recording, that's fine -  turn off your camera, and (if you wish) also remove your name from the screen. The videos will *only* be available on request if needed, and *all* videos will be deleted at the end of the semester. 

9) you WILL need a computer for this class. If you need to borrow one please let me know. 

I'm looking forward to seeing you all on Friday. There's a light at the end of the tunnel...we'll get there together.  

Excelsior!

 

