---
title: "LAS 6292: PAPERLESS DATA COLLECTION (IN-CLASS)"
date: "updated: `r Sys.Date()`"
header-includes:
   - \usepackage[default]{sourcesanspro}
   - \usepackage[T1]{fontenc}
mainfont: SourceSansPro
geometry: margin=1in
fontsize: 12pt
linkcolor: blue
urlcolor: blue
output:
  pdf_document: default
  html_document:
    df_print: paged
  rmdformats::robobook: default
---


```{r setup, include=FALSE}
library(knitr)
library(rmdformats)

## Global options
options(max.print="75")
opts_chunk$set(echo=FALSE,
	             cache=TRUE,
               prompt=FALSE,
               tidy=TRUE,
               comment=NA,
               message=FALSE,
               warning=FALSE)
opts_knit$set(width=75)
```



# Part 1: Using EpiCollect5 to gather data.

## Install the App and Gather some data

1. Download the Epicollect5 app and install it on a phone or tablet.

    * Available for [Android](https://play.google.com/store/apps/details?id=uk.ac.imperial.epicollect.five&hl=en_US&gl=US) and [Apple OS](https://apps.apple.com/us/app/epicollect5/id1183858199)

2. Open the Epicollect5 app and tap  "+ Add Project"

3. In the "searech "Search" box, write "squirrel" and select the project "Squirrels of Gainesville" when it appears

4. The project will have been added to the home screen. Tap on the SOG project to open it.

5. Click the three vertical dots in the upper right hand corner and select "Project Info" from the menu. This will give you a few more details about the project; when done reading it tap "Back" to return to the home page.

6. Now you are ready to gather some data. Go outside and take a nice walk. When you see squirrel, tap "+ Add entry". Enter the required data.  

7. After you enter the final data and read the "Read Me" message, you will tap the boxes for uploading the data, uploading the picture, and uploading the audio. 

7. Keep collecting data until you have data for three squirrels or 20 minutes have passed. 


## Reviewing the data

1. Open the [EpiCollect5 website](https://five.epicollect.net/) and login with your Google account

2. Once you have logged on, select "Find Project"

3. Select "Search." The search box is a bit tough to find - it's on the far left under "General", and is indicated by the text "Filter Projects by Name". Search for the project "Squirrels of Gainesville" and click "View".

4. Once you have opened the project page, you can "View Data" (go ahead!) and then download the data as a csv file.

5. Submit the csv file as Part 1 of the homework.



# Part 2: Create a form using EpiCollect

1. After logging into the website, select "My Projects" in the upper right  

2. Click "Create Project"

3. You have a choice - either create a project and data collection form for YOUR data collection OR...

4. ....convert either of the 'paper' data sheets into an Epicollect online form.

5. Regardless of which you chose to do (yours or one of these), you must include (at least) the following:

    * Date
    * Time 
    * Location
    * A text field for the name of the data collector, subject, etc.
    * One dropdown menu question
    * One radio button question
    * One checkbox question
    * One set of questions that is "Grouped"
    * One set of questions requiring "jumps"
    * A Read_me box with instructions, contact information, IRB information, or similar.
    * Project Settings: Public, Active, Hidden
    

5. When done, submit the link to your project as Part 2 of the homework. 


6. PS Here is the [EpiCollect user's guide](https://docs.epicollect.net/)
