---
title: "Bruna Lab Fieldwork Checklist"
date: "updated: `r Sys.Date()`"
header-includes:
- \AtBeginDocument{\let\maketitle\relax} # this removes default title section
- \usepackage[default]{sourcesanspro}
- \usepackage{fancyhdr} # modify header into left, center, right
- \pagestyle{fancy} # cues the use of fancy headers
- \fancyfoot{} # cues the use of fancy footer
# month & year on header left
- \fancyhead[L]{Bruna Lab Fieldwork Checklist} 
# name and page on header right
- \fancyhead[R]{p. \thepage} 
- \fancyfoot[R]{Last update `r format(Sys.time(), '%d %B %Y')`}
# - \usepackage{setspace}{singlespace} # manipulate line spacing 
- \usepackage{parskip} # manipulate indents and spacing before/after paragra phs 
- \usepackage{xcolor} # changes colors of text
# to center to top level (#) headings (my name) and change color of font
# more info # https://www.ctan.org/pkg/sectsty
- \usepackage{sectsty} \sectionfont{\centering\color{darkmidnightblue}}
# to center to sub-sub-headings (###) and change color of font
- \usepackage{sectsty} \subsectionfont{\color{darkmidnightblue}}
# http://latexcolor.com/ to choose colors
# define the colors used above with rgb codes
- \definecolor{darkcerulean}{rgb}{0.03, 0.27, 0.49}
- \definecolor{darkmidnightblue}{rgb}{0.0, 0.2, 0.4}

mainfont: SourceSansPro
geometry: margin=1in
fontsize: 12pt
linkcolor: blue
urlcolor: blue
output: pdf_document
# html_document:
# df_print: paged
# rmdformats::robobook: default
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
<!-- - [ ] Item -->
<!-- - [x] Item -->

<!-- https://www.sciencedirect.com/topics/medicine-and-dentistry/first-aid-kit -->

# First Aid

These items from the CDC's [_'Advice for Travelers'_ website](https://wwwnc.cdc.gov/travel/page/pack-smart)

## Prescription medicines

- [ ] Your prescriptions
- [ ] Travelers’ diarrhea antibiotic
- [ ] Medicines to prevent malaria

## Medical supplies

- [ ] Glasses and contacts
- [ ] Medical alert bracelet or necklace
- [ ] Diabetes testing supplies
- [ ] Insulin
- [ ] Inhalers
- [ ] EpiPens


## Over-the-counter medicines

- [ ] Diarrhea medicine (Imodium or Pepto-Bismol)
- [ ] Antacid
- [ ] Antihistamine
- [ ] Motion sickness medicine
- [ ] Cough drops, cough suppressant, or expectorant
- [ ] Decongestant
- [ ] Pain and fever medicine (acetaminophen, aspirin, or ibuprofen)
- [ ] Mild laxative
- [ ] Mild sedative or sleep aid

## Supplies to prevent illness or injury

- [ ] Hand sanitizer (containing at least 60% alcohol) or antibacterial hand wipes
- [ ] Water purification tablets
- [ ] Insect repellent (with an active ingredient like DEET or picaridin)
- [ ] Sunscreen (with UVA and UVB protection, SPF 15 or higher)
- [ ] Sunglasses and hat
- [ ] Condoms
- [ ] Earplugs

## First-aid kit

- [ ] 1% hydrocortisone cream
- [ ] Antibacterial or antifungal ointments
- [ ] Digital thermometer
- [ ] Oral rehydration salts
- [ ] Antiseptic wound cleaner
- [ ] Aloe gel for sunburns
- [ ] Insect bite anti-itch gel or cream
- [ ] Bandages
- [ ] Disposable gloves
- [ ] Cotton swabs (Q-Tips)
- [ ] Tweezers
- [ ] Eye drops

# Documents

- [ ] Copies of your passport and travel documents
- [ ] Copies of all prescriptions (medications, glasses, or medical supplies)
- [ ] Health insurance card and documents
- [ ] Proof of yellow fever vaccination (if required for your trip)
- [ ] Contact card with the street addresses, phone numbers, and e-mail addresses of:     - [ ] Family member or close contact in the United States
    - [ ] Health care provider(s) at home
    - [ ] Lodging at your destination
    - [ ] Hospitals or clinics (including emergency services) in your destination
    - [ ] US embassy or consulate in the destination country or countries


