---
title: "Checklist - Solomon Islands Research Project"
date: "updated: `r Sys.Date()`"
header-includes:
- \AtBeginDocument{\let\maketitle\relax} # this removes default title section
- \usepackage[default]{sourcesanspro}
- \usepackage{fancyhdr} # modify header into left, center, right
- \pagestyle{fancy} # cues the use of fancy headers
- \fancyfoot{} # cues the use of fancy footer
# month & year on header left
- \fancyhead[L]{Vehicle Checklist} 
# name and page on header right
- \fancyhead[R]{p. \thepage} 
- \fancyfoot[R]{Last update `r format(Sys.time(), '%d %B %Y')`}
# - \usepackage{setspace}{singlespace} # manipulate line spacing 
- \usepackage{parskip} # manipulate indents and spacing before/after paragra phs 
- \usepackage{xcolor} # changes colors of text
# to center to top level (#) headings (my name) and change color of font
# more info # https://www.ctan.org/pkg/sectsty
- \usepackage{sectsty} \sectionfont{\centering\color{darkmidnightblue}}
# to center to sub-sub-headings (###) and change color of font
- \usepackage{sectsty} \subsectionfont{\color{darkmidnightblue}}
# http://latexcolor.com/ to choose colors
# define the colors used above with rgb codes
- \definecolor{darkcerulean}{rgb}{0.03, 0.27, 0.49}
- \definecolor{darkmidnightblue}{rgb}{0.0, 0.2, 0.4}

mainfont: SourceSansPro
geometry: margin=1in
fontsize: 12pt
linkcolor: blue
urlcolor: blue
output: pdf_document
# html_document:
# df_print: paged
# rmdformats::robobook: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

<!-- - [ ] Item -->

<!-- - [x] Item -->

<!-- https://www.sciencedirect.com/topics/medicine-and-dentistry/first-aid-kit -->

## Monthly Vehicle & Vessel Checklist (1st of each month)

<!-- _This checklist is essential to safety and comfort while driving / hauling_ -->

<!-- ### Month:________ -->

### Check washer fluid in trucks

-   [ ] 2022 F150
-   [ ] 2018 F150
-   [ ] F250

### Check tire pressure, tread depth, & condition (rot, spidering, etc.)

-   [ ] 2022 F150
    -   [ ] tire pressure (35 psi)
    -   [ ] condition & tread depth
-   [ ] 2018 F150
    -   [ ] tire pressure (35 psi)
    -   [ ] condition & tread depth
-   [ ] F250
    -   [ ] tire pressure (80 psi)
    -   [ ] condition & tread depth
-   [ ] Sea Ark trailer
    -   [ ] tire pressure (50 psi)
    -   [ ] condition & tread depth
-   [ ] Twinvee trailer
    -   [ ] tire pressure (65 psi)
    -   [ ] condition & tread depth

-   [ ] Parker trailer
    -   [ ] tire pressure (65 psi)
    -   [ ] condition & tread depth
-   [ ] Jon Boat trailer
    -   [ ] tire pressure (80 psi)
    -   [ ] condition & tread depth
-   [ ] SRP box trailer
    -   [ ] tire pressure (50 psi)
    -   [ ] condition & tread depth
-   [ ] Flatbed trailer
    -   [ ] tire pressure (50 psi)
    -   [ ] condition & tread depth


\newpage

## Triannual Vehicle/Vessel Checklist (every 4 months during colunteer stay)

<!-- _To be completed once during volunteer stay (every 4 months). This checklist is essential to safety and comfort while driving / hauling_ -->

<!-- ### Month: _______ -->

### Check trailer hub grease (Impurities? Water?)

-   [ ] Sea Ark trailer
-   [ ] Twinvee trailer
-   [ ] Parker trailer
-   [ ] Jon Boat trailer
-   [ ] SRP box trailer
-   [ ] Flatbed trailer

### Lubricate trailer couplers, jack, and jack hinge

-   [ ] Sea Ark trailer
-   [ ] Twinvee trailer
-   [ ] Parker trailer
-   [ ] Jon Boat trailer
-   [ ] SRP box trailer
-   [ ] Flatbed trailer

### Check spare tires on trailers

-   [ ] Sea Ark trailer
    -   [ ] tire pressure
    -   [ ] tire condition
    -   [ ] mount condition
-   [ ] Twinvee trailer
    -   [ ] tire pressure
    -   [ ] tire condition
    -   [ ] mount condition
-   [ ] Parker trailer
    -   [ ] tire pressure
    -   [ ] tire condition
    -   [ ] mount condition
-   [ ] Jon Boat trailer
    -   [ ] tire pressure
    -   [ ] tire condition
    -   [ ] mount condition
-   [ ] SRP box trailer
    -   [ ] tire pressure
    -   [ ] tire condition
    -   [ ] mount condition
-   [ ] Flatbed trailer
    -   [ ] tire pressure
    -   [ ] tire condition
    -   [ ] mount condition

### Check voltage on boat batteries

-   [ ] Sea Ark
-   [ ] Twinvee
-   [ ] Parker
-   [ ] Jon Boat

### spare tires on trucks: pressure and condition (eg., rotting, spidering, etc.)

-   [ ] 2022 F150
    -   [ ] tire pressure
    -   [ ] condition & tread depth
-   [ ] 2018 F150
    -   [ ] tire pressure
    -   [ ] condition & tread depth
-   [ ] F250
    -   [ ] tire pressure
    -   [ ] condition & tread depth

### Charge battery jump boxes (in office)

-   [ ] Both black/yellow boxes
