---
title: "Curating Chaos - Session Outlines"
author: "Emilio M. Bruna"
date: "1/7/2021"
output:
  pdf_document: default
  
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

DEFINITELY DO:

Draft DMP submission, which is peerr reviewed by a another (or 2)  student (grade the submission and peer review)

Draft code cleanup submission with peer coding revieww

R studio cloud

### 4. Reproducible data (re)organization  

for next year
1. covert live-coding file in Rmd file to hand out OR into R demo 
2. Make the sample r file downloadable
1. count the steps exercise -  make a figure or do an analysis, change a variable, and count the number of steps involved.



* **Intro Material (lecture/videos): **
  * https://dataoneorg.github.io/Education/lessons/09_analysis/index 
  * https://dataoneorg.github.io/Education/bp_step/analyze/ 
  * https://dataoneorg.github.io/Education/bp_step/collect/
  * https://dataoneorg.github.io/Education/bp_step/integrate/


### 5. Data validation & correction 1
* **Intro Material (lecture/videos): **

QA/QC: finding and fixing mistakes. Best way is not to make them.


MAKE A VIDEO ABOUT THIS
Finding and fixing mistakes: 
Before R: have it read the data back to you immediately.

A.	Reading back
https://www.dataquest.io/blog/load-clean-data-r-tidyverse/
INSIDE OF R STUDIO
https://rpubs.com/williamsurles/291107 
B.  Plotting different ways
B.	Summary calculations
C.	Randomly sampling from  digital file to verify
find spelling mistakes in factors; add new ones if needed
find and remove duplicate rows
correct data types
find outliers
find and replace strings
split columns
find missing data
remove white space at start and end

F.	MOST IMPORTANT: DO NOT FIX RAW DATA FILE. Txt file with changes that need to be made, then make them with a scripting language


* **In-class Exercise:** 
  * visualizations to help find errors, working on own datasets


### 6. Data validation & correction 2
* **Intro Material (lecture/videos): **
  * review of all that needs to be done: https://dataoneorg.github.io/Education/bp_step/assure/

* **In-class Exercise:**  
    * Data Carpentry Lesson (2:15 h)
    * https://datacarpentry.org/openrefine-socialsci/
    * https://datacarpentry.org/OpenRefine-ecology-lesson/


### 7. Documentation: Metadata, Codebooks   

https://www.youtube.com/watch?v=N2zK3sAtr-4


* 	Understands the concept of, and rationale for, metadata
* 	Identify and list the types of information typically included in metadata records
* 	Identify applicable standards for documenting and capturing metadata in your discipline
* 	Familiar with tools for creating metadata appropriate for your discipline and data type
* 	Formulate an approach to creating metadata for a project
* 	Develops an ability to read and interpret metadata from external disciplinary sources



it is hard to explain to someone how to do stuff, what things mean
example exercise of the importance of detailed instructions: definitions

build-a-sandwhich reporducibility exercise (they do instructions, i will make on screen trying to follow! don't tell them I'm going to do it, ask them to do it and then spring it on them),

* **Intro Material (lecture/videos): **
  * https://dataoneorg.github.io/Education/lessons/07_metadata/index 
  * https://dataoneorg.github.io/Education/bp_step/describe/ 

* **In-class Exercise:** Begin Drafting Metadata File, Code Books


### 8. Data Management Plans   
* **Intro Material (lecture/videos): **
  * https://dataoneorg.github.io/Education/lessons/03_planning/index 
  * https://dataoneorg.github.io/Education/bp_step/integrate/

* **In-class Exercise:** DMP tool to start buildling their own DMP    
      
### 9. Efficient data collection   

* **In-class Exercise:** build a better form, find error minimization

### 10. Transcription & Translation   

* **In-class Exercise:** compare different transcription / translation tools

### 11. ‘Paperless’ data collection   

* **In-class Exercise:** build epicollect file and collect data withit

### 12. Automated data extraction   

* **In-class Exercise:** Compare OCR tools

### 13. Legal and Ethical Issues  

* 	Explain ownership considerations related to data sharing
* 	Explain and evaluate potential legal issues connected to your data; intellectual property, copyright claims, licenses needed for use, monetary charges for data
* 	Explain ethical considerations related to data sharing
* 	Understand privacy levels for research data as required by potential funding agencies
* 	Recognize the importance of privacy with some forms of research data (HIPAA)
* 	Understand the importance of removing key personal identifiers to facilitate confidentiality



* **Intro Material (lecture/videos): **https://dataoneorg.github.io/Education/lessons/10_policy/index



### 14. Data Sharing, Reuse, & Archives   
*understand advantages of data sharing and archiving
*discuss concerns and and obstacles related to data sharing
*understand restrictions on reuse of data, software, and instrumentation, including different CCO and Public Domain licences)
*adress reuse / sgharing requiorements from granting aqgencies or sponsors

*understand options for maximizing data reuse
*understand data identifiers and what they are for
* underrstand benefits of using unique researcher id in metadata

*	Identify types of available repositories/archives (discipline-based, institutional, etc.)
*	Chooses appropriate option for long-term storage of data
*	Understand process issues for depositing data in repository


* **Intro Material (lecture/videos): **
  * https://dataoneorg.github.io/Education/lessons/02_datasharing/L02_Exercise.pdf
  * https://dataoneorg.github.io/Education/lessons/08_citation/index
  * https://dataoneorg.github.io/Education/bp_step/discover/

* **In-class Exercise:**  Find data, look at data archive and see if they can understand it





---
title: "Resources"
author: "Emilio M. Bruna"
date: "1/2/2021"
output: pdf_document
---



# for linguistics
https://onlinelibrary.wiley.com/doi/10.1002/9781444301120.ch3

https://www.cambridge.org/core/journals/bilingualism-language-and-cognition/article/towards-a-credibility-revolution-in-bilingualism-research-open-data-and-materials-as-stepping-stones-to-more-reproducible-and-replicable-research/C4FC0550EE4537D8603942419B288C6E

Linguistics in R
https://benjamins.com/sites/z.195/content/package.html
https://slcladal.github.io/corplingr.html
https://cran.r-project.org/web/packages/languageR/languageR.pdf




# Qualtrix
Importing Qualtrics Data into R
https://www.adrianbruegger.com/post/import-qualtrics-csv-files/


# Class Exercises & Resources

resources from SAGE: https://study.sagepub.com/corti2e + new edition of book https://us.sagepub.com/en-us/nam/managing-and-sharing-research-data/book262873#resources

videos, exercises, etc from Corti book 2nd Edition https://study.sagepub.com/corti2e


# For Intro Lecture: What is "Data" in different dfisciplines? 
humanities
https://campus.dariah.eu/resource/ws2019#session-2
https://escholarship.umassmed.edu/cgi/viewcontent.cgi?referer=http://scholar.google.com/&httpsredir=1&article=1115&context=jeslib 
https://www.routledge.com/The-Digital-Humanities-Coursebook-An-Introduction-to-Digital-Methods-for/Drucker/p/book/9780367565756
https://methods.sagepub.com/book/the-sage-handbook-of-qualitative-data-analysis/n32.xml 

"In these fields, the concepts of “data” and “evidence” are very nuanced. However, virtually all information you record during your research counts as such. Here are some common (yet not exhaustive) examples of data captured in the arts, humanities and social sciences: 1) Focus group notes 2) Fieldwork notes 3) Finding aids https://en.wikipedia.org/wiki/Finding_aid
4) Interviews (audio/video) and transcriptions 5) Interview coding 6) Meeting minutes 7) Text corpora https://en.wikipedia.org/wiki/Text_corpus 8) Text with markup https://port.sas.ac.uk/mod/book/view.php?id=568&chapterid=335
Thematic research collections http://digitalhumanities.org/companion/view?docId=blackwell/9781405103213/9781405103213.xml&chunk.id=ss1-4-5&toc.id=0&brand=9781405103213_brand 9) Digitised books, paintings and other works of art 


# GUIDES: 
Briney KA, Coates H, Goben A (2020) Foundational Practices of Research Data Management. Research Ideas and Outcomes 6: e56508. https://doi.org/10.3897/rio.6.e56508

Goodman A, Pepe A, Blocker AW, Borgman CL, Cranmer K, Crosas M, et al. (2014) Ten Simple Rules for the Care and Feeding of Scientific Data. PLoS Comput Biol 10(4): e1003542. https://doi.org/10.1371/journal.pcbi.1003542

Burley, T.E., and Peine, J.D., 2009, NBII-SAIN Data Management Toolkit, U.S. Geological Survey Open-File Report 2009-1170, 96 p. Available from: http://pubs.usgs.gov/of/2009/1170/

https://www.dcc.ac.uk/guidance
https://wildlife.onlinelibrary.wiley.com/doi/10.1002/wsb.548 


## humanities (general)
*  https://archive.mith.umd.edu/dhcuration-guide/guide.dhcuration.org/legal/policy.html  

## history 
*  https://www.historians.org/jobs-and-professional-development/professional-life/resources-for-graduate-students/graduate-school-from-start-to-finish/aha-guide-to-archival-research
*  https://www.historians.org/publications-and-directories/perspectives-on-history/october-2017/data-management-plans-for-historians-how-to-document-and-protect-your-research
*  https://www.arcgis.com/apps/Cascade/index.html?appid=032048097a7f46f8b3b6859389e18124  


# **Tools**  

## Data Collection, Project Management, & Collaboration
* Data Stewardship Wizard (for DMPs, data management) https://ds-wizard.org/
*  [Open Science Framework](https://osf.io/)  
*  [Open Science Framework (free)](http://tinyurl.com/yaa8hph4)  
*  [Asana (monthly charge)](https://asana.com/)  
*  [Slack](http://tinyurl.com/y9bz8suj)  
*  Ellis, S. E., & Leek, J. T. (2018). How to share data for collaboration. The American Statistician, 72(1), 53-57.  
*  https://www.qsrinternational.com/nvivo-qualitative-data-analysis-software/home  
*  https://atlasti.com/ (nvivo and atlasti about the same purtpiose)  
*  https://zapier.com/pricing   
*  https://www.notion.so/  
*  https://www.devontechnologies.com/apps/devonthink
*  aeon visual timeline software https://www.aeontimeline.com/  
*  IFTT: https://ifttt.com/   
*  fiji: https://fiji.sc/ image processing anal;ysis  
*  https://www.taguette.org/ qualitative data research tool, all fields, exportable looks good  
*  scanning apps:  https://www.nytimes.com/wirecutter/reviews/best-mobile-scanning-apps/  
*  https://www.literatureandlatte.com/scrivener/overview  
* https://www.pinterest.com/ahahistorians/a-digital-tool-box-for-historians/

## Data Security

*  [UF Library Guidelines for Data Security](http://guides.uflib.ufl.edu/datamanagement/security)  
*  UF Office of Information Security and Compliance  
*  [Cyber Safeguards for UF](https://security.ufl.edu/wp-content/uploads/2012/12/data-security-handouts.pdf)  
*  [UF IT Information Security](https://security.ufl.edu/learn-information-security/protect-yourself/data/)  
*  [UF IRB )Data Record Storage and Security](http://irb.ufl.edu/index/data/1981-2.html)   
*  [UF Data Classification Policy](https://it.ufl.edu/policies/information-security/data-classification-policy/)   
*  [UF Office of Information Security and Compliance Cyber Safeguards for UF](https://security.ufl.edu/wp-content/uploads/2012/12/data-security-handouts.pdf)  
*  [data anonymizing is hard](https://onezero.medium.com/why-anonymized-data-isn-t-so-anonymous-535d2db75a2d)   

*  [Uploading](http://tinyurl.com/y9bz8suj)  

DataONE Best Practices Working Group, DataONE  (July 01, 2010) "Best Practice: Ensure integrity and accessibility when making backups of data". Accessed through the Data Management Skillbuilding Hub. [[read online]]( https://dataoneorg.github.io/Education/bestpractices/ensure-integrity-and) [download pdf]



## **Week 14: Data Sharing, Reuse, & Archives**  

*  https://www.authorea.com/users/260319/articles/436166-research-data-repositories-chosen-by-researchers-across-broad-range-of-disciplines-from-an-analysis-of-145-000-data-availability-statements?commit=05d5052a56e7ac63dd07d17fb88c47430b194874  

* read from [IPUMS](https://usa.ipums.org/usa/tutorials.shtml) directly into R with [this package](https://cran.r-project.org/web/packages/ipumsr/vignettes/ipums.html#:~:text=The%20ipumsr%20package%20allows%20you,integrated%20across%20time%20and%20space).

huge list of archives: https://www.nature.com/sdata/policies/repositories 
*  [Qualitative Data Repository](https://qdr.syr.edu/)  
*  [google Dataset Search](https://datasetsearch.research.google.com/) and [explanatory blog post](https://blog.google/products/search/discovering-millions-datasets-web/)
*  [Cessda](https://www.cessda.eu/)
SMP


* Gregory K, Khalsa SJ, Michener WK, Psomopoulos FE, de Waard A, Wu M (2018) Eleven quick tips for finding research data. PLoS Comput Biol 14(4): e1006038. https://doi.org/10.1371/journal.pcbi.1006038

*  Sielemann K, Hafner A, Pucker B. 2020. The reuse of public datasets in the life sciences: potential risks and rewards. PeerJ 8:e9954 https://doi.org/10.7717/peerj.9954  
*  Mauthner, N. S., & Parry, O. (2009). Qualitative data preservation and sharing in the social sciences: On whose philosophical terms?. Australian Journal of Social Issues, 44(3), 291-307.  
*  Baker, K. S., & Duerr, R. E. (2017). Research and the changing nature of data repositories. Curating Research Data, 33.
*  Whyte, A. & Wilson, A. (2010). How to Appraise and Select Research Data for Curation. DCC How-to Guides. Edinburgh: Digital Curation Centre. (also available online: http://www.dcc.ac.uk/resources/how-guides)  
*  UF Library Guide: http://guides.uflib.ufl.edu/datamanagement/sharing
*  Bruna, E. M. 2010. Journals can advance tropical biology and conservation by requiring data archiving.  Biotropica 42(4): 399–401  
*  Piwowar, H. A., & Vision, T. J. (2013). Data reuse and the open data citation advantage. PeerJ, 1, e175.    
*  Michener WK. 2015. Ecological data sharing. Ecological Informatics. 2015 Sep 1;29:33-44.    
*  Participants _want_ their data shared: https://onlinelibrary.wiley.com/doi/abs/10.1002/eahr.500044   



