---
title: "LAS 6292: RESOURCES FOR TRANSCRIPTION & TRANSLATION"
date: "updated: `r Sys.Date()`"
header-includes:
   - \usepackage[default]{sourcesanspro}
   - \usepackage[T1]{fontenc}
mainfont: SourceSansPro
geometry: margin=1in
fontsize: 12pt
linkcolor: blue
urlcolor: blue
output:
  pdf_document: default
  html_document:
    df_print: paged
  rmdformats::robobook: default
---


```{r setup, include=FALSE}
library(knitr)
library(rmdformats)
knitr::opts_chunk$set(echo = TRUE)
## Global options
options(max.print="75")
opts_chunk$set(echo=FALSE,
	             cache=TRUE,
               prompt=FALSE,
               tidy=TRUE,
               comment=NA,
               message=FALSE,
               warning=FALSE)
opts_knit$set(width=75)
```



## Translation 

### Upload (Free)  
        
1. [Google Translate](https://translate.google.com/) and [help documents](https://support.google.com/docs/answer/4492226?hl=en#zippy=%2Cadd-punctuation).  
    
2. [DeepL](https://www.deepl.com/translator)  

### Upload (Limited Free + Paid)

1. [Otter.ai](https://otter.ai/login). English only; free (600 min/mo) and paid plans. Can transcribe zoom meetings (e.g., if you do interviews via zoom) and can [integrate with Dropbox](https://blog.otter.ai/otter-dropbox-integration/). Phone app is available for [iOS](https://play.google.com/store/apps/details?id=com.aisense.otter&hl=en_US&gl=US)

2. [Happy Scribe](https://www.happyscribe.com/). 40+ languages. 30 min. free then paid; [student pricing available](https://www.happyscribe.com/audio-to-text-for-students). Can integrate with Zapier to up/download files from [Google Drive](https://zapier.com/apps/happy-scribe/integrations/google-drive) and [Dropbox](https://zapier.com/apps/happy-scribe/integrations/dropbox)

3. [Temi](https://www.temi.com/). English Only, less accurate than Otter.ai and Happy Scribe.

4. [Spext](https://www.spext.co/). Speech-audio-text editing; free and paid plans.

5. Online demi version of [Watson](https://speech-to-text-demo.ng.bluemix.net/); note the "detect multiple speakers" option.

6. [Translate Shell](https://www.soimort.org/translate-shell/#translate-shell)

7. [Comparison Video](https://www.youtube.com/watch?v=GAmkIHJl7A0 comparisons)

### via API (free, paid)

1. [```googleLanguageR```](https://docs.ropensci.org/googleLanguageR/). Uses the Google Cloud machine learning APIs for text and speech tasks. The [Cloud Translation API](https://cloud.google.com/translate/) does detection and translation of text. 

2. [```aws.translate```](https://github.com/cloudyr/aws.translate) uses the Amazon Web Services to do transcription via API. Has program for NGO/non-profits.

3. [```translate```](https://cran.r-project.org/web/packages/translate/index.html) Another translator via Google API

4. [```translateR```](https://cran.r-project.org/web/packages/translateR/index.html) Yet another translator via Google API.

5. [Watson (IBM)](https://cloud.ibm.com/catalog/services/speech-to-text) 500 minutes free

6. [DeepL](https://www.deepl.com/translator)

7. [Translate Shell](https://www.soimort.org/translate-shell/#translate-shell) via API

6. [Zoom](https://video.ufl.edu/conferencing/zoom/captions-and-live-transcription/)


### Manual Transolation with Computer Assisted Technology (CAT) Software

1. [Tools](https://www.youtube.com/watch?v=nbxBV_7QEyk)

2. [OmegaT CAT Software](https://omegat.org/). Free software

3. [WordFast Anywhere](https://www.wordfast.com/products_wordfast_anywhere) is free, online (desktop version are paid)

4. [Across.net](https://www.across.net/). Basic version is free 


### Translation Resources 

1. [Linguee](https://www.linguee.com/) Good for slang and expressions;searches different ways in which one word has been translated. Can also enter several words or even a sentence to find different translations.

2. [Thesaurus.com](Thesaurus.com); equivalent in foreign language.

3. Side-by-Side [Text Comparison Website](https://www.diffchecker.com/diff)


## Audio Transcription

### Automated via upload (limited free, paid)

2. [Otter.ai](https://otter.ai/login) and [online tutorial](https://www.youtube.com/watch?v=SCaBnObVsqI)

3. [Amazon Transcribe](https://aws.amazon.com/transcribe/)

### Automated via API (paid)

1. [```transcribeR```](https://cran.r-project.org/web/packages/transcribeR/index.html) uses HP IDOL OnDemand's Speech Recognition API. You can read a tutorial [here](http://www.micha-dietze.de/pages/r_texts/_book/kaleidoscope.html)

2. [```googleLanguageR```](https://docs.ropensci.org/googleLanguageR/). Uses the Google Cloud machine learning APIs for text and speech tasks. The [Cloud Speech API](https://cloud.google.com/speech/) transcribes sound files to text and the Cloud Text-to-Speech AP

3. [```AWS transcribe```](https://github.com/cloudyr/aws.transcribe) uses the Amazon Web Services to do transcription via API. Has program for NGO/non-profits.

### Manual via software (free, paid)

1. [oTranscribe](https://otranscribe.com/)  Incredibly easy, web based, with time stamps, variable speed.

1. [Express Scribe](Transcription Software https://www.nch.com.au/scribe/index.html) and [a tutorial](https://www.youtube.com/watch?v=kbKRJcd1ueA). There is a free version.

2. [Transcribe](https://transcribe.wreally.com/)

3. [Nvivo](https://www.qsrinternational.com/nvivo-qualitative-data-analysis-software/about/nvivo/modules/transcription)

4. [Listen N Write](https://download.cnet.com/Listen-N-Write/3000-2170_4-75416316.html)

5. [InScribe](https://www.inqscribe.com/)


## Text Transcription (via dictation)

1. [Google Docs](https://www.google.com/docs)

1. [SpeechNotes](https://speechnotes.co/)


## Resources & Tools

1. Guide to capturing and processing [images for archiving](https://guides.uflib.ufl.edu/celebratingcuba/digitization#s-lg-box-wrapper-29381548)  

2. Examples of Transcription Notes
    
    * [Sample 1](https://ufdc.ufl.edu/AA00062074/00001/pdf)
    
    * [Sample 2](http://www.gutenberg.org/files/21829/21829-h/21829-h.htm)


3. Guide to [Transcription Coding](https://guides.uflib.ufl.edu/celebratingcuba/translation-transcription#s-lg-box-25015800)

4. Style Guides

    * Samuel Proctor Project [Style Guide](https://ufdc.ufl.edu/IR00002513/00001)

    * Library of Congress [Transcription Guide](https://crowd.loc.gov/help-center/how-to-transcribe/)

    * Smithsonian Archives of American Art [Style Guide](https://www.aaa.si.edu/documentation/oral-history-program-style-guide)
    
    * Smithsonian Volunteer Transcription Program [Guide](https://transcription.si.edu/instructions) and [Expert Tips](https://transcription.si.edu/articles/insights-tips-volunpeer-expert-transcribe-style)


5. Foot Pedals

    * [Infinity](https://www.amazon.com/Infinity-Digital-Control-Computer-USB2/dp/B002MY6I7G/)
    
    * [Kinesis](https://kinesis-ergo.com/products/#foot-switches)

6. Text Shortcuts
    
    * [Google Docs](https://www.howtogeek.com/448511/how-to-use-text-shortcuts-in-google-docs/)
    * [MS Word](https://wordribbon.tips.net/T006829_Inserting_Text_with_a_Shortcut_Key.html#:~:text=Position%20the%20insertion%20point%20in,commands%20currently%20using%20this%20shortcut.)

# Sources

1. Michael Henry Heim & Andrzej W. Tymowski. [Guidelines for the Translation](https://www.acls.org/uploadedFiles/Publications/Programs/sstp_guidelines.pdf)
of Social Science Texts. American Council of Learned Societies

2. Jennifer Marie's YouTube channel on [Transcription Tools & Tips](https://www.youtube.com/channel/UC-ooPg34j8PK3osA4l-726Q) 

3. Sophie Chabeda, Jane Kahindi, Manya Van Ryneveld. [Preparing data: the not-so-simple stage of transcription and translation](https://globalhealthsocialscience.tghn.org/articles/preparing-data-not-so-simple-stage-transcription-and-translation/)

4. Squires, A. (2009). [Methodological challenges in cross-language qualitative research: A research review.](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2784094/pdf/nihms98173.pdf). International Journal of Nursing Studies, 46(2), 277-287.

5. Hepburn, A., & Bolden, G. B. (2017). [Transcribing for social research](https://uk.sagepub.com/en-gb/eur/transcribing-for-social-research/book237847). Sage.

6. McLellan E, MacQueen KM, Neidig JL. Beyond the Qualitative Interview: Data Preparation and Transcription. Field Methods. 2003;15(1):63-84. [doi:10.1177/1525822X02239573](https://journals.sagepub.com/doi/10.1177/1525822X02239573)

7. MacLean LM, Meyer M, Estable A. Improving Accuracy of Transcripts in Qualitative Research. Qualitative Health Research. 2004;14(1):113-123. [doi:10.1177/1049732303259804](https://doi.org/10.1177/1049732303259804)

8. Hughes, M. [Are Online Transcription Services Safe and Private?](https://www.howtogeek.com/657944/are-online-transcription-services-safe-and-private/). How-to-Geek.