---
title: "LAS 6292: Week 10: In-Class Breakout 1"
date: "updated: `r Sys.Date()`"
header-includes:
   - \usepackage[default]{sourcesanspro}
   - \usepackage[T1]{fontenc}
mainfont: SourceSansPro
geometry: margin=1in
fontsize: 12pt
linkcolor: blue
urlcolor: blue
output:
  pdf_document: default
  html_document:
    df_print: paged
  rmdformats::robobook: default
---


```{r setup, include=FALSE}
library(knitr)
library(rmdformats)
knitr::opts_chunk$set(echo = TRUE)
## Global options
options(max.print="75")
opts_chunk$set(echo=FALSE,
	             cache=TRUE,
               prompt=FALSE,
               tidy=TRUE,
               comment=NA,
               message=FALSE,
               warning=FALSE)
opts_knit$set(width=75)
```

## **GROUPS**  

* Group 1: mandarin1_text.docx, spanish_text.docx
    
* Group 2: mandarin2_text.docx, indonesian_text.docx


## STEP 1. Translate

Translate the text files within MS Word and Google Docs  

* Google Docs: [in-doc translation](https://support.google.com/docs/answer/187189?co=GENIE.Platform%3DDesktop&hl=en) (create a new google doc, cut-and-paste the text into the Google Doc, save it, and translate)

* MS Word: [in-doc translation](https://support.microsoft.com/en-us/topic/translate-text-into-a-different-language-287380e4-a56c-48a1-9977-f2dca89ce93f) 



## **STEP 2.** Save

Save the translations in your Google Drive in a folder called "class_translations" with the following file names and formats:

* MS Word: txt file: `MSWord_[original language]_to_english.txt`  

* Google: new GoogleDoc: `google_[original language]_to_english`  
    
## **STEP 3.** Compare

* Paste the translations into the Text Comparison Website [https://www.diffchecker.com/diff](https://www.diffchecker.com/diff)

* You may have to adjust the spacing in the text files to make the text align.  

## **STEP 4. **Discuss  

* Are there are any differences in the way key words or concepts were translated? 

* Are there circumstances under which these could influence the interpretation of the writer's intent? Subtleties of language like formality of tense, tone, or meaning?

* Do any of them seem "better" or "more accurate"? 

