---
title: "LAS 6292: Intro to Reproducibile Data Cleanup in R"
date: "updated: `r Sys.Date()`"
header-includes:
- \AtBeginDocument{\let\maketitle\relax} # this removes default title section
- \usepackage[default]{sourcesanspro}
- \usepackage{fancyhdr} # modify header into left, center, right
- \pagestyle{fancy} # cues the use of fancy headers
- \fancyfoot{} # cues the use of fancy footer
# month & year on header left
- \fancyhead[L]{LAS 6292 Spring `r format(Sys.time(), '%Y')`, EM Bruna} 
# name and page on header right
- \fancyhead[R]{Reproducibility, p. \thepage} 
- \fancyfoot[R]{Last update `r format(Sys.time(), '%d %B %Y')`}
# - \usepackage{setspace}{singlespace} # manipulate line spacing 
- \usepackage{parskip} # manipulate indents and spacing before/after paragra phs 
- \usepackage{xcolor} # changes colors of text
# to center to top level (#) headings (my name) and change color of font
# more info # https://www.ctan.org/pkg/sectsty
- \usepackage{sectsty} \sectionfont{\centering\color{darkmidnightblue}}
# to center to sub-sub-headings (###) and change color of font
- \usepackage{sectsty} \subsectionfont{\color{darkmidnightblue}}
# http://latexcolor.com/ to choose colors
# define the colors used above with rgb codes
- \definecolor{darkcerulean}{rgb}{0.03, 0.27, 0.49}
- \definecolor{darkmidnightblue}{rgb}{0.0, 0.2, 0.4}
mainfont: SourceSansPro
geometry: margin=1in
fontsize: 12pt
linkcolor: blue
urlcolor: blue
output: pdf_document
knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile,
  encoding = encoding,
  output_dir = "./static/uploads")
  })
---

```{r setup, include=FALSE}
library(knitr)
library(rmdformats)

## Global options
options(max.print="75")
opts_chunk$set(echo=FALSE,
	             cache=TRUE,
               prompt=FALSE,
               tidy=TRUE,
               comment=NA,
               message=FALSE,
               warning=FALSE)
opts_knit$set(width=75)
```

# Intro to Reproducibile Data Cleanup in R

## 1. Set up an RStudio Project

1. File -> New Project
1. Name the Project as follows: `las_demo`
1. Create the following three folders: 

   `data_raw`  
   `data_clean`  
   `code`  
  
## 2. Download the data we will be using in class

1. Open the messy data file `demo_data.csv` by following [this link](https://github.com/BrunaLab/LAS6292_DataManagement/blob/05dd4970756f635a41bdefbff4ef0e18183639ae/content/course-materials/class-sessions/04-reproducibility/examples/demo_data.csv)
1. click the **`[Raw]`** button on the right hand side above the data; 
1. the data will open as a tab in your web browser in `*.csv` format; save them to the `data_raw` folder by going to 'File' on the menu bar of your web browser and selecting 'Save page as' from the drop-down menu.
1. save the file to the `data_raw` folder. 

## 3. Data Cleaning: Overview

1. _Characteristics of clean data set include:_

   * Free of duplicate rows/values
   * Error-free (correct misspellings, eliminate special characters)
   * correct data type for analysis
   * outliers identified and dealt in the correct way
   * “tidy" data structure

2. _Take your data from `messy` to `clean` in 5 steps_  
    
   *  Familiarize yourself with the data set
   *  Check for structural errors
   *  Check for data irregularities
   *  Decide how to deal with missing values

## 4. Data Cleaning: Practice

### 1. Review the Data Set

1. Review the `.csv` file 
2. What things do you see that need to be corrected? 
3. Make a list of the what you think needs to be corrected and the steps necessary to identify and implement each correction. Some of the things to look out for include: 
    
    * Numeric values stored as character data types
    * Factors stred as characters
    * Duplicate rows
    * Spelling mistakes
    * inconsistent formatting (eg., codes, capitalizations)
    * White spaces
    * Missing data
    * Zeros instead of null values
    * Special characters (e.g. commas in numeric values instead of decimals)
    * column headings with spaces between words or that start with numerals 
      
### 2. Import

1. Create a new `.r` file and save it as `cleanup_code` in your `code` folder
2. Annotate your code and key info: session info(), name and what for, etc.
3. Load `tidyverse` library
4. [quick step back]: load file into R and go over 2 ways to look it over: (a) in the viewer and (b) using commands `str` and `glimpse`
5. This is a good time to go over the difference between `base R` and `Tidyverse`

### 3. Make changes

1. read and edit column names
1. change Data Types
1. change values in a column `tolower` or `toupper` 
1. Correct a spelling mistake # Point out that these sometimes go away with `tolower`
1. order factor
1. add a column
1. add a calculation
1. group (`case_when`)

### 4. Export clean data

1. save as a `.csv` file in the `data_clean` folder
2. Opening the clean `.csv` with excel to verify the changes are there

### 5. Reproduce your results

1. Sweep the environment
2. restart r
3. rerun your code to make sure it works
      
## 5. KEY MESSAGES

1. Keep raw data raw. Always.
2. Annotate. Lots.

## In-Class Exercise

<!-- https://dataoneorg.github.io/Education/lessons/09_analysis/09_analysis.pdf -->
<!-- https://www.dataquest.io/blog/load-clean-data-r-tidyverse/  -->

### 1. Load and Review

Start the process of identifying the corrections and  rearranging that needs to be done with your data. No need to code it yet, but make a list of it a .r file. We will look this over and divide it into logical blocks of steps.

### 2. Make Corrections

1. Standardize the titles
1. Take the raw_data, find any thing that needs to be corrected
(spelling mistakes, etc)
2. convert any "NA" to "missing"
3. convert factor levels in 'roof' and 'wall' to codes to make easier to read
4. convert 'rooms' to factor, then back to numeric
5. save as a csv

### 3. Save the data

### 4. Submit

1. When done, you submit a screen shot of the Rstudio project. If you have any r scripts submit them as well. 

# Tools & Resources

1. These introductions to R and R Studio were made by Professor Ethan White (UF-WEC). They are a good overview of some R basics.  

      * [Intro to R and RStudio](https://www.youtube.com/watch?v=zqUQL8OOtMQ).
      * [Navigate R and RStudio web page](https://swcarpentry.github.io/r-novice-gapminder/01-rstudio-intro/index.html)
      * [Intro to R Packages](https://www.youtube.com/watch?v=NAArCsmztOI)
      * [Expressions and Variables in R](https://www.youtube.com/watch?v=BFVX0CKY67g&feature=emb_title)
      
1. The Carpentries' R workshops (self-paced or taught in-person) are excellent, I use many of their materials in class: 
  
    * [R for Social Scientists](https://datacarpentry.org/r-socialsci/)
    * [Data Analysis and Visualization in R for Ecologists](https://datacarpentry.org/R-ecology-lesson/)

1. Software Carpentry lesson on [Project Management with R Studio](https://swcarpentry.github.io/r-novice-gapminder/02-project-intro/) 

1. Hadley Wickham wrote a book on using the tidyverse and the [online version is FREE](https://r4ds.had.co.nz/). This is a phenomenal resource on using R to import, tidy, and visualize data. 

2. [RStudio Cheat Sheets](https://rstudio.com/resources/cheatsheets/): help with commands for using the different `tidyverse` packages, RStudio shortcuts and tricks, help with R commands, and more. You definitely want the ones for Data Import, Work with Strings, Factors, Data Transformation, and Base R.

3. Where and How to ask for help  

    * Hadley Wickham's advice on [how to write a good reproducible example]((http://adv-r.had.co.nz/Reproducibility.html)) for getting help with R
    * [how to post good questions on StackOverflow](https://www.r-bloggers.com/2011/01/three-tips-for-posting-good-questions-to-r-help-and-stack-overflow/)
    * The UF [R-users listserv](http://www.r-gators.com/listserv/) is *very* user friendly and a great place to post requests for help. 

1. [Ten simple rules for biologists learning to program](https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1005871)

4. Lot's more on the course's ['Resources' page](https://las6292.netlify.app/docs/resources/) 

# Additional (interesting) Reading

1. Lewis, Keith P., Eric Vander Wal, and David A. Fifield. 2018. Wildlife biology, big data, and reproducible research. Wildlife Society Bulletin 42(1): 172-179.  

1. White EP, Baldridge E, Brym ZT, Locey KJ, McGlinn DJ, Supp SR.  2013.  Nine simple ways to make it easier to (re)use your data. Ideas in Ecology and Evolution. 6(2):1-10.  

1. [The humanities have a ‘reproducibility’ problem](https://talkinghumanities.blogs.sas.ac.uk/2019/07/09/the-humanities-have-a-reproducibility-problem/)

1. [The humanities do not need a replication drive](https://www.cwts.nl/blog?article=n-r2v2a4&title=the-humanities-do-not-need-a-replication-drive)

1. [Reproducible Research: A primer for the social sciences](http://benmarwick.github.io/CSSS-Primer-Reproducible-Research)

1. [Replicability and replication in the humanities](https://researchintegrityjournal.biomedcentral.com/articles/10.1186/s41073-018-0060-4)

1. [Towards reproducible science in the digital humanities](https://dhh.uni.lu/2020/05/19/towards-reproducible-science-in-the-digital-humanities-how-to-publish-your-data-and-code-alongside-your-research-with-the-help-of-zenodo/)

1. [The possibility and desirability of replication in the humanities](https://www.nature.com/articles/s41599-018-0149-x)

1. [Reproducible Research: A Retrospective](https://www.annualreviews.org/doi/10.1146/annurev-publhealth-012420-105110#_i18)

**_For when you feel more comfortable with R and programming_**

1. Bryan, J. (2018). Excuse me, do you have a moment to talk about version control? The American Statistician, 72(1), 20-27.

1. Wilson, Greg, Jennifer Bryan, Karen Cranston, Justin Kitzes, Lex Nederbragt, and Tracy K. Teal. Good enough practices in scientific computing. PLoS Computational Biology 13, no. 6 (2017): e1005510.  


<!-- 4. [Reproducible Research in the Humanities](https://www.slideshare.net/IainEmsley/reproducible-research-in-the-humanities) -->
<!-- 4. https://oxford.universitypressscholarship.com/view/10.1093/oso/9780190670412.001.0001/oso-9780190670412-miscMatter-11 -->
<!-- 1. [Reproducible Data Science](https://ecorepsci.github.io/reproducible-science/)  -->


