---
title: "Generic DMP Template"
date: "updated: `r Sys.Date()`"
header-includes:
- \AtBeginDocument{\let\maketitle\relax} # this removes default title section
- \usepackage[default]{sourcesanspro}
- \usepackage{fancyhdr} # modify header into left, center, right
- \pagestyle{fancy} # cues the use of fancy headers
- \fancyfoot{} # cues the use of fancy footer
# header left
- \fancyhead[L]{Generic DMP Template} 
# header right
- \fancyhead[R]{p. \thepage} 
- \fancyfoot[R]{Last update `r format(Sys.time(), '%d %B %Y')`}
# - \usepackage{setspace}{singlespace} # manipulate line spacing 
- \usepackage{parskip} # manipulate indents and spacing before/after paragra phs 
- \usepackage{xcolor} # changes colors of text
# to center to top level (#) headings (my name) and change color of font
# more info # https://www.ctan.org/pkg/sectsty
- \usepackage{sectsty} \sectionfont{\centering\color{darkmidnightblue}}
# to center to sub-sub-headings (###) and change color of font
- \usepackage{sectsty} \subsectionfont{\color{darkmidnightblue}}
# http://latexcolor.com/ to choose colors
# define the colors used above with rgb codes
- \definecolor{darkcerulean}{rgb}{0.03, 0.27, 0.49}
- \definecolor{darkmidnightblue}{rgb}{0.0, 0.2, 0.4}
mainfont: SourceSansPro
geometry: margin=1in
fontsize: 12pt
linkcolor: blue
urlcolor: blue
output:
  pdf_document: default
  # html_document:
  #   df_print: paged
  # rmdformats::robobook: default
---
## Generic DMP Template: 

**1. Project, experiment, and data description**

- What’s the purpose of the research?
-	What is the data? How and in what format will the data be collected? Is it numerical data, image data, text sequences, or modeling data?
-	How much data will be generated for this research?
-	How long will the data be collected and how often will it change?
-	Are you using data that someone else produced? If so, where is it from?
-	Who is responsible for managing the data? Who will ensure that the data management plan is carried out?


**2. Documentation, organization, and storage**

-	What documentation will you be creating in order to make the data understandable by other researchers?
-	Are you using metadata that is standard to your field? How will the metadata be managed and stored?
-	What file formats will be used? Do these formats conform to an open standard and/or are they proprietary?
-	Are you using a file format that is standard to your field? If not, how will you document the alternative you are using?
-	What directory and file naming convention will be used?
-	What are your local storage and backup procedures? Will this data require secure storage?
-	What tools or software are required to read or view the data?


**3.	Access, sharing, and re-use**

-	Who has the right to manage this data? Is it the responsibility of the PI, student, lab, university, or funding agency?
-	What data will be shared, when, and how?
-	Does sharing the data raise privacy, ethical, or confidentiality concerns?  Do you have a plan to protect or anonymize data, if needed?
-	Who holds intellectual property rights for the data and other information created by the project? Will any copyrighted or licensed material be used? Do you have permission to use/disseminate this material?
-	Are there any patent- or technology-licensing-related restrictions on data sharing associated with this grant? The institutional Technology Licensing Office (TLO) can provide this information.
-	Will this research be published in a journal that requires the underlying data to accompany articles?
-	Will there be any embargoes on the data?
-	Will you permit re-use, redistribution, or the creation of new tools, services, data sets, or products (derivatives)? Will commercial use be allowed?


**4.	Archiving**

-	How will you be archiving the data? Will you be storing it in an archive or repository for long-term access? If not, how will you preserve access to the data?
-	Is a discipline-specific repository available? If not, you could consider depositing your data into the university repository. Email us at data-management@mit.edu if you’re interested in using DSpace@MIT to store your data.
-	How will you prepare data for preservation or data sharing? Will the data need to be anonymized or converted to more stable file formats?
-	Are software or tools needed to use the data? Will these be archived?
-	How long should the data be retained? 3-5 years, 10 years, or forever?

