---
title: "LAS 6292: QA/QC 2 - OpenRefine"
date: "updated: `r Sys.Date()`"
header-includes:
   - \usepackage[default]{sourcesanspro}
   - \usepackage[T1]{fontenc}
mainfont: SourceSansPro
geometry: margin=1in
fontsize: 12pt
linkcolor: blue
urlcolor: blue
output:
  pdf_document: default
  html_document:
    df_print: paged
  rmdformats::robobook: default
---


```{r setup, include=FALSE}
library(knitr)
library(rmdformats)

## Global options
options(max.print="75")
opts_chunk$set(echo=FALSE,
	             cache=TRUE,
               prompt=FALSE,
               tidy=TRUE,
               comment=NA,
               message=FALSE,
               warning=FALSE)
opts_knit$set(width=75)
```

## Objectives and Competencies:  

OpenRefine (formerly Google Refine) is a powerful, free, and open source tool that is used to work with and clean messy data. By the end of this lesson students will:

1. Be able to import a dataset into OpenRefine, make changes to the dataset and its structure, and export the revised Dataset.  

2. Learn how to automatically track changes made and export the record of changes

## Pre-class Preparation (Students):

1. Install OpenRefine on your computer and verify it works by following the [instructions here](https://datacarpentry.org/openrefine-socialsci/setup.html).

2. Scan the [basic workflow](https://hackmd.io/WnKT7eiMQde7jCF5teVHBQ#Setup) for what we will be doing.

3. Read about OpenRefine and see some quick videos of [how it works here](https://openrefine.org/)


## Lessons & Resources Used in Class

1. The Data Carpentry Lesson we did with Dr. Ye: [OpenRefine for the Social Sciences](https://datacarpentry.org/openrefine-socialsci/) 

2. The repository with the data and metadata used in the lesson:  [SAFI_Survey](https://figshare.com/articles/dataset/SAFI_Survey_Results/6262019)

3. URL for accessing OpenRefine if a new tab/window doesn't open: http://127.0.0.1:3333/

4. Guides for writing OpenRefine commands with General Refine Expression Language
    
    * [OpenRefine GREL](https://docs.openrefine.org/manual/expressions/#grel-general-refine-expression-language)
    * a great [GREL Guide](https://guides.library.illinois.edu/openrefine/grel) from the Univ Illinois
    * EVEN BETTER: [OpenRefine cheatsheets](https://code4libtoronto.github.io/2018-10-12-access/GoogleRefineCheatSheets.pdf), including GREL commands 

## Other OpenRefine tools and tutorials

1. [Cleaning Data with OpenRefine](https://doi.org/10.46430/phen0023): a tutorial from *The Programming Historian* website 

2. Data Carpentry Lesson: [OpenRefine for Ecologists](https://datacarpentry.org/OpenRefine-ecology-lesson/00-getting-started/)
# Sources

3. Cleaning Data with OpenRefine [Video Tutorial No. 1](https://www.youtube.com/watch?v=nORS7STbLyk) and [Video Tutorial No. 2](https://www.youtube.com/watch?v=xZlz4ISgNBc)

## UF Library Workshops

1. The schedule of [UF Library Workshops](https://ufl.libcal.com/calendar/workshops/?cid=11693&t=d&d=0000-00-00&cal=11693,5125,8858&inc=0)

    * [Tidy Tuesday with Hao](https://ufl.libcal.com/event/7377304): practice data manipulation, clean-up, and analysis using the `tidyverse` with Dr. Hao Ye.
    
    * An [upcoming OpenRefine workshop](https://ufl.libcal.com/event/7345725) by Dr. Hao Ye (March 30,2021) 
