---
title: "LAS 6292 Breakout Week 2: Field Data Backup"
# author: "Emilio M. Bruna"
date: "updated: `r Sys.Date()`"
header-includes:
   - \usepackage[default]{sourcesanspro}
   - \usepackage[T1]{fontenc}
mainfont: SourceSansPro
geometry: margin=1in
fontsize: 12pt
linkcolor: blue
urlcolor: blue
# output: rmdformats::downcute
output:
  pdf_document: default
  html_document:
    df_print: paged
  rmdformats::robobook: default
---
### BREAKOUT EXERCISE: FIELD DATA STORAGE AND BACKUP
Robin is a graduate student studying Malaria in Tanzania. The research project requires visiting communities, collecting mosquitos from different sources of standing water (for later identification at the FLMNH and statistical analyses of mosquito diversity and abundance) and conducting semi--structured interviews in the community, where people are asked such things as their age, family income, their access to health care, if they have ever had malaria, their family income, use of mosquito nets. Answers are recorded on data sheets, but the interviews are also recorded with the cell phone for later transcription. Robin also takes pictures of houses to document standing water sources. Throughout the day Robin records observations in a notebook.  

Robin is staying in a house where there is electricity for a laptop. Once every two weeks Robin goes into town, where there is usually good internet access at the university. 

What steps should Robin take in the field to safeguard the data collected in the field? 




