---
# title: 'LAS 6292: Week 1 - Survey'
# author: "Emilio M. Bruna"
# date: "`r format(Sys.time(), '%Y')`"
output:
  word_document: default
  html_document: default
  pdf_document: default
---
<!-- Note: to rendr as pdf delete the \newline -->
#### **LAS 6292: WEEK 2 IN-CLASS ASSIGNMENT** 
#### **Spring Semester 2021**
\newline  
\newline   
**This week’s assignment is designed to:** **(A)** get you thinking critically about your own data backup and security procedures, and based on that reflection **(B)** prepare a data backup plan (if you already have one you can answer the questions below based on that plan).  **The assignment comes in four parts:**   

\newline  
\newline  
1. Sign up for a UF Dropbox allocation (if you don’t already have one)  
\newline
\newline
2. Sign up for a UF GSuite / Google Drive Allocation (if you don’t already have one)  
\newline
\newline
3. Briefly describe how you are adhering to the 3-2-1 backup rule for data related to your thesis. If you aren’t, please describe the things you will do to rectify this.  
\newline
\newline
4.	Prepare a brief (1~ page max) Data Backup Plan for your thesis research. Include the following information:   
\newline
\newline  

    a.	what needs to be prepared and for how long
  
  
    b.	where backups are located  
    
    c.	who can access backups and how contacted  
  
    d.	how often data should be backed up  
    
    e.	what kind of backups are performed  
  
    f.	who is responsible for performing the backups  
  
    g.	hardware and software used for performing backups  
  
    h.	how / how often to check if backups is successful  
  
    i.	the media are used to backup data  
  
    j.	a list of any data that are  not archived or backed up  
  
    
      
**Note: **You can respond with bullet points unless more detailed answers are needed.  
  
  
  
  

  

  **Grading Rubric: **  
1) Assignment completed with thorough answers: 50  
2) Most questions answered completely; some require instructor follow-up: 40  
3) Many questions missing answers or answers are cursory: 30   
4) Instructor follow-up required for homework submission: 20
