---
title: "LAS 6292 Breakout Week 2: Backup Interview"
# author: "Emilio M. Bruna"
date: "updated: `r Sys.Date()`"
header-includes:
   - \usepackage[default]{sourcesanspro}
   - \usepackage[T1]{fontenc}
mainfont: SourceSansPro
geometry: margin=1in
fontsize: 12pt
linkcolor: blue
urlcolor: blue
# output: rmdformats::downcute
output:
  pdf_document: default
  html_document:
    df_print: paged
  rmdformats::robobook: default
---
### DATA PROTECTION AND BACKUP INTERVIEW

Please ask each other these questions and then briefly discuss and summarize the responses. Keep the answers anonymous. The goal is to document the range of answers to these questions, so you can summarize or give more detailed answers about individuals as needed.
 

1.	Does your advisor / lab / research group have formal policies that govern your data storage, protection, and backup?

2.	Are you currently backing up your research data?

3.	Do you have a ‘backup plan’ document?

4.	How frequently are you backing up your research data? 

5.	Is it Partial (incremental) or full backup? 

6.	Where are files backed up? 

7.	What metadata accompanies these backups? 

8.	How do you verify that a backup has been successfully performed? 

9.	Have you ever attempted to read data from older backups? 

10.	Have you ever had to restore a file from a backup version?

11.	Are you working with data requiring additional protection due to privacy or security concerns? 

12.	If so, what are the additional safeguards you have implemented?

13.	Where and how are your original data collection instruments or samples stored/protected?

